### ISSUE TITLE
exception in get_serializer_class()

### ISSUE THREAD

**Issue by Mendes11** [tfranzel/drf-spectacular#102]
The following view:

```python3
class ClientsDashboardView(generics.ListCreateAPIView):
    serializer_class = ClientDashboardSerializer
    queryset = Client.objects.all()
    filterset_class = ClientFilter
    authentication_classes = (SessionAuthentication, TokenAuthentication)
    permission_classes = (permissions.IsAuthenticated,)

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return ClientDashboardSerializer
        return ClientSerializer

    @extend_schema(request=ClientSerializer,
                   responses=ClientSerializer)
    def create(self, *args, **kwargs):
        return super(ClientsDashboardView, self).create(*args, **kwargs)

    @extend_schema(responses=ClientDashboardSerializer)
    def list(self, *args, **kwargs):
        return super(ClientsDashboardView, self).list(*args, **kwargs)

    def get_queryset(self):
        qs = super(ClientsDashboardView, self).get_queryset()
        if not self.request.user.has_perm('api.can_see_all_clients'):
            qs = qs.filter(users__id=self.request.user.id)
        return qs

    def filter_queryset(self, queryset):
        qs = super(ClientsDashboardView, self).filter_queryset(queryset)
        return sorted(qs, key=lambda x: x.global_score)
```

Happens to throw the error:
`Error #0: Exception raised while getting serializer from ClientsDashboardView. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'NoneType' object has no attribute 'method')`

As the error says, the problem is with request.method.

What should I do in these cases? I tried using extend_schema in create and list methods but that didn't solve the error...

**Comment by tfranzel** [comment]
uhh that was tough to see 😄. pretty sure you "override" the wrong methods and the API works because DRF uses the default implementations. your ``create`` and ``list`` are likely never called by either DRF or spectacular.

https://github.com/encode/django-rest-framework/blob/master/rest_framework/generics.py#L238

for ``ListCreateAPIView`` (and in essence``APIView``) you only have ``get``, ``post`` and so on. ``create`` ``list`` is for views derived from the ``ViewSet`` hierarchy. 

apart from that you did everything right. when you use ``@extend_schema`` for all ""method x req x res" cases (as you did), ``get_serializer`` and ``get_serializer_class`` is never called.

**Comment by Mendes11** [comment]
> for ListCreateAPIView (and in essenceAPIView) you only have get, post and so on. create list is for views derived from the ViewSet hierarchy.

Actually as the link shows it calls the `list` and `create` methods since `ListCreateAPIView` implements `ListModelMixin` and `CreateModelMixin`. 
(Just to be sure I set a debugger and called the view normally using DRF and the `list` method was called). Now the `APIView` indeed doesn't call these methods.

But indeed, when I put post and get methods it worked!

```python3
    @extend_schema(responses=ClientSerializer, request=ClientSerializer)
    def post(self, *args, **kwargs):
        return super(ClientsDashboardView, self).get(*args, **kwargs)

    @extend_schema(responses=ClientDashboardSerializer)
    def get(self, *args, **kwargs):
        return super(ClientsDashboardView, self).post(*args, **kwargs)
```

**Comment by tfranzel** [comment]
sry you are right. list exists, you override and it is indeed used, but that was not the problem. it is complicated to explain. suffice it so say that it breaks DRF magic with regards to how the schema class is discovered, because you decorated an inner action instead of the outmost routed action utilized by ``urlpatterns`` and ``.as_view()``.

having a mock request everywhere would have made it easier. the overrides would not have been necessary. that feature is on the todo list. in the meantime this should also work (notice the `action`) given that you have a router in your project:

```python
class ClientsDashboardView(mixins.CreateModelMixin, mixins.ListModelMixin, GenericViewSet):
    serializer_class = ClientDashboardSerializer
    queryset = Client.objects.all()
    filterset_class = ClientFilter
    authentication_classes = (SessionAuthentication, TokenAuthentication)
    permission_classes = (permissions.IsAuthenticated,)

    def get_serializer_class(self):
       # action is only available for ViewSets
        if self.action == 'retrieve':
            return ClientDashboardSerializer
        return ClientSerializer

    def get_queryset(self):
        qs = super(ClientsDashboardView, self).get_queryset()
        if not self.request.user.has_perm('api.can_see_all_clients'):
            qs = qs.filter(users__id=self.request.user.id)
        return qs

    def filter_queryset(self, queryset):
        qs = super(ClientsDashboardView, self).filter_queryset(queryset)
        return sorted(qs, key=lambda x: x.global_score)
```

**Comment by Mendes11** [comment]
I see, thanks for the explanation! I'm closing this issue.
