### ISSUE TITLE
Supporting for Json Schema Draft 2020 and OpenAPI 3.1

### ISSUE THREAD

**Issue by Fares-Abubaker** [tfranzel/drf-spectacular#1071]
Hello,

What exactly is the latest Json Schema Draft and OpenAPI supported?

**Comment by tfranzel** [comment]
Hi, 

there is none. We are currently generating OpenAPI 3.0.3 which is not yet json schema compliant. Compliance starts with OpenAPI 3.1. We have not implemented it yet because upstream support was very slow to change and I have not found an elegant way to run the test suite against 2 versions yet. We will eventually support it though.

https://github.com/tfranzel/drf-spectacular/pull/825

**Comment by tfranzel** [comment]
https://github.com/tfranzel/drf-spectacular/issues/378#issuecomment-1879656965

As I said there, we now have support for OpenAPI 3.1. The generated schemas are valid against JSON Schema 2020-12, which is guaranteed by validation against:
