### ISSUE TITLE
got multiple values for keyword argument 'context

### ISSUE THREAD

**Issue by Lepiloff** [tfranzel/drf-spectacular#1072]
Django 3.2/ DRF 3.14.0  
When forming a page with api documentation, an error is observed in the console

`got multiple values for keyword argument 'context'`

Code sample

```
class CustomBatchView(mixin.ListModelMixin, mixin.CreateModelMixin, VendorViewSetMixin):
       def_serializer(self, *args, **kwargs):
            context = {'request': self.request}
            if self.action == 'create':
                return BatchCreateSerializer(*args, context=context, **kwargs)
            elif self.action in ['update', 'partial_update']:
                return BatchUpdateSerializer(*args, context=context, **kwargs)
            else:
                return BatchSerializer(*args, context=context, **kwargs)
```
            
            
The problem is that when **Viewsets** in DRF calls `get_serializer`, it passes context inside `kwargs`. So when I try to pass the `context` separately, there is a conflict.
    
So if implement this

```
        if 'context' in kwargs:
            del kwargs['context']
```
inside  `get_serializer`
All work perfect.  
Such a problem does not arise with business logic. Only at the moment of forming API documentation. What can this be related to and how can it be fixed?

**Comment by tfranzel** [comment]
I see. That makes total sense. Not sure how your `_serializer` is called but you changed the DRF's default behavior slightly. 

It is possible that you don't see this in business logic because we cannot 100% reproduce the code paths of DRF and there might be slight differences because of that. 

I see 2 options:

1. Use this instead of explicit `context` arg to add the request: `kwargs.setdefault("request", self.request)`. This is the same as `get_serializer()` is handling this and is better and safer.

2. change behavior for schema runs with this marker: https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-get-queryset-depends-on-some-attributes-not-available-at-schema-generation-time

**Comment by Lepiloff** [comment]
Thank you!
