### ISSUE TITLE
Order of properties is not consistent when using camelize_serializer_fields post processing hook

### ISSUE THREAD

**Issue by antoineauger** [tfranzel/drf-spectacular#1084]
First of all, thank you for this great Django plugin 🚀 🐍 

**Describe the bug**
When using [camelize_serializer_fields](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/contrib/djangorestframework_camel_case.py) post-processing hook, the order of the properties is not consistent between several schema generations.

The reason is because the property list is never really sorted (see [here](https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/contrib/djangorestframework_camel_case.py#L43)), which leads to unpredictable results.

**To Reproduce**
Generate several times an OpenAPI schema with properties and `camelize_serializer_fields` post processing hook:

```python
...
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
        "drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields",
    ],
...
```
The more properties you have in your schema, the more likely the generated schema will be different (using an exact diff comparison).

**Expected behavior**
At minima, I would expect the properties to be alphabetically sorted. But we could also have a dedicated setting (e.g. `SORT_PROPERTIES`) to enforce that. Exactly like `SORT_OPERATIONS` and `SORT_OPERATION_PARAMETERS`.

**Comment by tfranzel** [comment]
Interesting issue you are raising there. The problem is that we do have tests for this extensions and they never fail against a fixed reference yaml: 

https://github.com/tfranzel/drf-spectacular/blob/master/tests/contrib/test_djangorestframework_camel_case.py 
https://github.com/tfranzel/drf-spectacular/blob/master/tests/contrib/test_djangorestframework_camel_case.yml

If what you are saying is accurate, those tests would have to be flaky once in a while, which they are not.

We iterate serializer fields in the order DRF provides via `serializer.fields.values()`, and the recoding of the properties dict (in this extension) is a simple list comprehension that should retain the order as given.

The stable insertion order (and iteration) of a dict is an implementation detail in python 3.6 and a guaranteed feature since 3.7. Hence, I'm unsure how it is possible that you are observing noisy output. Can you provide a reproduction for this?

**Comment by antoineauger** [comment]
@tfranzel Thanks for the quick answer, it really helps!

You're totally right, I hadn't seen these tests for this extension so this made me think that the problem was already there on the generated schema _before_ it gets applied. 

In fact, the problem only occurs for serializers inheriting from `ModelSerializer` that declare additional fields so this is consistent with what you said:

> We iterate serializer fields in the order DRF provides via serializer.fields.values(), and the recoding of the properties dict (in this extension) is a simple list comprehension that should retain the order as given.

To give a bit more context, we use `djangorestframework-jsonapi` in combination with a custom schema class generator inheriting from `AutoSchema` so the reproduction was not easy.

I think we can close this issue since the processing hook is clearly not in cause here and that I now know how to fix this 😅
