### ISSUE TITLE
Remove Authorize button while using custom authentication backend

### ISSUE THREAD

**Issue by Style77** [tfranzel/drf-spectacular#1087]
Hey I use custom authentication backend for saving JWT tokens in cookies. Everything works fine in swagger-ui but I'm getting this error 

```
Warning [ProviderAuthView]: could not resolve authenticator <class 'authorization.authentication.JWTCookiesAuthentication'>. There was no OpenApiAuthenticationExtension registered for that class. Try creating one by subclassing it. Ignoring for now.
``` 

so i tried to create extension like that:

```py
class JWTCookiesScheme(OpenApiAuthenticationExtension):
    target_class = "authorization.authentication.JWTCookiesAuthentication"
    name = "JWTCookiesAuthentication"
    match_subclasses = True
    priority = 1

    def get_security_definition(self, auto_schema):
        return {
        }
``` 
It works fine, however it feels like there shouldn't be any authorize button while using this approach, how can i disable it?

I don't think you need it but here is my authentication backend code
```py
class JWTCookiesAuthentication(JWTAuthentication):
    def authenticate(self, request):
        header = self.get_header(request)

        if header is None:
            raw_token = request.COOKIES.get(settings.SIMPLE_JWT['AUTH_COOKIE']) or None
        else:
            raw_token = self.get_raw_token(header)
        if raw_token is None:
            return None

        validated_token = self.get_validated_token(raw_token)
        return self.get_user(validated_token), validated_token
```

I also import this extension in serializers which doesn't feel right, where do you think i should import it? I tried importing in both settings.py and __init__.py but it throws an error.

**Comment by tfranzel** [comment]
Hi!

the default auth extension does not allow subclasses, which is why your custom class was not picked up. Since you target **your** class in **your** extension, the `match_subclasses` is not really needed.

---

> It works fine, however it feels like there shouldn't be any authorize button while using this approach, how can i disable it?

That is a different question. We have a setting for that. You can hide your auth methods in the schema, thus implicitly removing the button by setting `[]`

https://github.com/tfranzel/drf-spectacular/blob/6e4180b7175e4fd07d09f1c9820c0aa40553f001/drf_spectacular/settings.py#L162-L163

However, just removing the button always seemed hacky to me. Also, `return {}` may be an invalid schema. You may want to look at this:
https://github.com/tfranzel/drf-spectacular/blob/6e4180b7175e4fd07d09f1c9820c0aa40553f001/drf_spectacular/contrib/rest_auth.py#L149

Looks similar to `dj_rest_auth.JWTCookieAuthentication`, where you have 2 choices for the auth (header or cookie). This extension properly models that situation. You may want to adapt it to your needs.

---
> I also import this extension in serializers which doesn't feel right, where do you think i should import it? I tried importing in both settings.py and init.py but it throws an error.

yeah that is not good. we have a FAQ entry for that:

https://drf-spectacular.readthedocs.io/en/latest/faq.html#where-should-i-put-my-extensions-my-extensions-are-not-detected

**Comment by Style77** [comment]
Thank you it worked!
