### ISSUE TITLE
Swagger UI display issues

### ISSUE THREAD

**Issue by Whatislove118** [tfranzel/drf-spectacular#1108]
**Describe the bug**
I have this configuration:

```
SPECTACULAR_SETTINGS = {
    "TITLE": "LIME CITY API",
    "VERSION": __version__,
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    # OTHER SETTINGS
}

```

But on documentation page, I see this:

<img width="1440" alt="image" src="https://github.com/tfranzel/drf-spectacular/assets/56884186/90808c2a-a43e-4c1f-91f4-23fdaeca3461">

What am I doing wrong? What problem could affect a swagger like this?
**To Reproduce**
macbook m1 pro, sonoma 14.0. django=4.2.6, drf=3.14.0, chrome=119.0.6045.123

**Comment by tfranzel** [comment]
Likely a bug in SwaggerUI, since we only use the latest upstream version by default.

https://github.com/tfranzel/drf-spectacular/issues/1107#issuecomment-1808820846

**Comment by Amirshox** [comment]
downgrade swagger cdn, default @latest. it worked for me

`SPECTACULAR_SETTINGS = {
    ....
    'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.3',
}`

**Comment by tfranzel** [comment]
@Amirshox thanks for confirming and providing a working version

The reason we do not pin the SwaggerUI version by default is because this very rarely happens (2x in 3 years). Usually the issue is fixed upstream very quickly as **a lot** of people hit this. 

Given the rarity of actual problems, this is imho better than constantly "shipping" a moderately to severely outdated version (like drf-yasg). 

@beggy If this small risk is not acceptable to you, please feel free to manually pin the version for good. It is the recommended approach if you need more than 99.99% reliance.
