### ISSUE TITLE
Django 5 Support?

### ISSUE THREAD

**Issue by duaneking** [tfranzel/drf-spectacular#1126]
**Describe the bug**
Th readme mentions nothing about Django5 support.  Is this project abandoned?

**To Reproduce**
Look at the README.  Django 5 was release a bit ago but it doesn't seem to be officially supported, and that means this would block upgrades, right?

**Expected behavior**
I expect all modern released versions of Django to be supported, including 5+

**Comment by tfranzel** [comment]
I find you tone quite disrespectful. You are aware this is open-source and you pay nothing for the whole ecosystem, right?
The audaciousness to ask about abandonment when the last commit is 1 week ago. Check your privilege, man. 

Django 5 was released 5 days ago, not "a bit ago". I haven't even noticed yet, even though I also contributed to their release. What did you do? Also, `django-rest-framework` haven't even updated their README nor did they release a new version yet.  
Maybe you should also open an issue there and ask about abandonment. Pretty sure you will get a similar answer. 
This is a very mature stack with hundreds of people contributing their personal time **for free**. Your expectations with regards to promptness are way out of alignment.

Now, is there even anything broken? Usually new releases work 98% even if they are not yet mentioned in the README. How about contributing by running the tests and adding Django5 to the test suite instead of acting entitled?

**Comment by duaneking** [comment]
So to be clear, you are getting triggered by my attempt to be helpful? 🤣 

I cared enough to file the bug. I did that to be helpful, casually, 🤷‍♂️ 

 Most do not even do that. 😭 
 
I cant control if you get offended or not 🦺  but it honestly feels like your just getting offended and dismissive because I dared to help. If the bug didn't have enough emojis to help you understand my good intentions, sorry, but you should understand that tone in text is extremely hard to communicate and that your making bad assumptions, respectfully.

I was being succinct and helpful; you are assuming bad intent where non exists. 😞

**Comment by tfranzel** [comment]
> So to be clear, you are getting angry by my attempt to be helpful? 😢

No, I can assure you it is not helpful. 

> I cared enough to file the bug. I did that to be helpful, casually, 🤷‍♂️

If you actually cared, you would have written something more akin to: 
```
Hi! Have you noticed yet that Django 5 is out? I tested my codebase with Django 5 
against the most recent drf-spectacular version and it looks good with no changes 
or regressions. Can we add official support for it? Thanks.
```

> I was being succinct and helpful; you are assuming bad intent where non exists.

You should let other be the judge of that. The absence of bad intent does not make it acceptable.


Considering your name and location, I'm assuming your first language is english. With all due respect, unless your are somehow handicapped, I believe you should be able to appreciate how your message can be seen as passive aggressive, entitled and demanding. Furthermore, you don't get a ignorance bonus, like a junior would, with a 10 year old account. You should know better by now how to interact with the community. Especially when you boast about your soft skills in your profile.  

This project is has been constantly active for over 3 years: https://github.com/tfranzel/drf-spectacular/graphs/contributors
Asking about abandonment - out of nowhere - with a activity graph like that is super disrespectful to all the people contributing here.

Out of the +1000 personal interactions this project has received, you made the top 3 most disrespectful. That is why I even bothered to answer. Looking at your recent github history, I can see that you have a habit of opening low quality issues that often don't even receive a response. Looks like I'm not the only one not having it. Maybe you should meditate on that.
