### ISSUE TITLE
Typing issue when `extend_schema` contained in dict literal

### ISSUE THREAD

**Issue by realsuayip** [tfranzel/drf-spectacular#1145]
**Describe the bug**
I have a module where I maintain all `extend_schema` definitions like so:

```python
from drf_spectacular.utils import extend_schema

a = extend_schema(summary="a")
b = extend_schema(summary="b")

f = {"a": a, "b": b}
```

Checking types gives following errors:

```
main.py:6: error: Dict entry 0 has incompatible type "str": "Callable[[F], F]"; expected "str": "Callable[[object], object]"  [dict-item]
main.py:6: error: Dict entry 1 has incompatible type "str": "Callable[[F], F]"; expected "str": "Callable[[object], object]"  [dict-item]
Found 2 errors in 1 file (checked 1 source file)
```

**To Reproduce**
Run `mypy>=1.6.0` on given Python script. The issue does not appear with `mypy==1.5.1` 

**Expected behavior**
No errors?

**Comment by tfranzel** [comment]
I can confirm this, however I do not know what exactly changed in mypy. The error seems incorrect to me, but I'm not very sure about that.

```python
a = extend_schema(summary="a")
b = extend_schema(summary="b")

F = TypeVar('F', bound=Callable[..., Any])

f: dict[str, Callable[[F], F]] = {"a": a, "b": b}
```

explicitly typing `f` fixes it for me. Maybe mypy is unable to recognize that both items share the same signature. Not sure if we even could change anything here to fix it otherwise.

**Comment by realsuayip** [comment]
I could not find anything related in mypy changelog either. I'll ask in mypy issues to have their feedback.
