### ISSUE TITLE
Is there any way to override 'Code' and 'Description' naming in Responses?

### ISSUE THREAD

**Issue by valeriyaduran** [tfranzel/drf-spectacular#1200]
Hello!
I looked through the docs https://drf-spectacular.readthedocs.io/en/latest/customization.html searching for customization of the generated schema. I found 'Step 6: Postprocessing hooks' may be suitable **for overriding 'Code' and 'Description' naming in Responses** **(highlighted in yellow on the attachment)** , but it does not.
So, the question is: Is there any way to do it using drf-spectacular library or maybe any other way to struggle with it?  
![responses](https://github.com/tfranzel/drf-spectacular/assets/36791323/0285cbe3-acd1-450c-8106-98bc0c7e2c7d)

**Comment by tfranzel** [comment]
You need to use `OpenApiResponse / Request` to reach that functionality because it is individual to the response code.

```python
@extend_schema(
    responses={
        200: OpenApiResponse(description="foo", response=SomeSerializer)
        201: OpenApiResponse(description="bar")
        400: OpenApiResponse(description="baz", response=dict)
    }
)
```

please refer to the docs on how to use the decorators: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-2-extend-schema

another example:

https://github.com/tfranzel/drf-spectacular/blob/4d6c93f083ad9cdd78ea934d921680225c935af5/tests/test_examples.py#L277-L290

**Comment by valeriyaduran** [comment]
Thank you, it is clear. But I asked about **naming** . I want to change **'description' to 'response data'**. And instead of **'code' write down 'message'** and put here some response message.

**Comment by tfranzel** [comment]
This is a SwaggerUI upstream issue. We just conveniently provide it through CDN. You need to ask this kind of stuff over there: 

https://github.com/swagger-api/swagger-ui

**Comment by valeriyaduran** [comment]
Thank you!
