### ISSUE TITLE
drf-spectacular and allauth

### ISSUE THREAD

**Issue by carlos54vidal** [tfranzel/drf-spectacular#1220]
Allauth is a library for implementing user registration and authentication. It redirects the endpoints (urls) definitions from the project app to the library folder, under "Lib\site-packages\allauth" path, which contains the urls.py, views.py, etc...
To do this, it imports the urls path (path('accounts/', include('allauth.urls')),)
How can drf-spectacular be configured to pick up this schema?

**Comment by tfranzel** [comment]
Hi @Dresdn, I can see that they added API endpoints in the `headless` module. Unfortunately, it looks like they concocted their own API view baseclass for this instead of using DRF. Although we are able to write extensions for non-DRF classes (e.g. Pydantic), their support is somewhat limited. 

If someone can come up with a gameplan for this, I'm all ears. It will certainly mean writing a couple view extensions.

**Comment by dontic** [comment]
@tfranzel I would like to help with this. I see that by creating their own implementation of `APIView`, `drf-spectacular` doesn't register the views neither by using `extend_schema` or `OpenApiViewExtension`.

I was thinking of creating a DRF wrapper for the headless functionality, kind of what `dj-rest-auth` was doing, but I would be duplicating code and it also seems just too convoluted to rewrite all the views and serializers when `allauth` already has all the functionality built in.

I personally cannot find a proper way to implement this, as far as know there is no way to "manually" create an endpoint in `drf-spectacular`, if you can point me in the right direction or have an idea of how this could be achieved I would love to hear it.

**Comment by JasonLovesDoggo** [comment]
perhaps just include the schema? https://allauth.org/docs/draft-api/spec/openapi.yaml

**Comment by dontic** [comment]
@JasonLovesDoggo the problem is that, because allauth uses their own APIView implementation, you cannot extend the schema as we're used to with drf-spectacular.

A similar thing happens with other libraries, for which extensions are needed, I haven't looked too much into this and I currently do not have time to fo into it. Leaving it here in case someone wants to go for it:

https://drf-spectacular.readthedocs.io/en/latest/blueprints.html

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo the problem is that, because allauth uses their own APIView implementation, you cannot extend the schema as we're used to with drf-spectacular.
> 
> A similar thing happens with other libraries, for which extensions are needed, I haven't looked too much into this and I currently do not have time to fo into it. Leaving it here in case someone wants to go for it:
> 
> https://drf-spectacular.readthedocs.io/en/latest/blueprints.html

Ah, yes, I was aware of that. However, my idea was to add an option to DRF-Spectacular to enable merging multiple OpenAPI schemas. I'm not entirely sure about the feasibility of implementing this, though.

**Comment by tfranzel** [comment]
@JasonLovesDoggo If you want to merge other OpenAPI schemas into the output of spectacular, you can write a postprocessing hook and modify the given schema to your needs: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks

@ced4death looks like they render their [own schema](https://docs.allauth.org/en/dev/release-notes/recent.html#id2). One could write a postprocessing hook that calls that code in `allauth`, and subsequently insert those schema parts into the spectacular schema.  Sounds doable, but I have not checked the details on their side.

**Comment by robin24** [comment]
Hi,

I was just researching how to do this myself and sadly didn't find any good answers, but stumbled across this issue.

Given that a few months have passed since the last comment was posted here, I was wondering if there are any new developments when it comes to including either all or part of the allauth-headless schema in the schema generated by drf-spectacular?

From my own searching it looks like a bunch of people are having this problem, and there is no clear solution currently...

**Comment by tfranzel** [comment]
@robin24,

so nothing fundamentally changed here. allauth has a handwritten(?) schema and no DRF views.

https://github.com/pennersr/django-allauth/blob/8db1da7bcbda2d4ffa1e230df4df50eeb9c557f2/allauth/headless/spec/doc/openapi.yaml

One would have to take that yaml, decompose it and only apply the parts that are relevant. This could be done with a postprocessing hook. However, I think this is a brittle approach as the schema is not generated directly from the code, which was kind of the point of drf-spectacular. I can't change the fact that allauth chose to go this custom non-compatible route. 

This looks like a time-intensive task, which I do not have the time for atm. If anyone want to give this a shot, be my guest. It has to meet a certain amount of robustness though. We should not just dump all of the schema into ours and be done with it I guess.
