### ISSUE TITLE
JSONFields with default=dict

### ISSUE THREAD

**Issue by SorianoMarmol** [tfranzel/drf-spectacular#1242]
First of all, thank you for all your effort!

**Describe the bug**

With the change related to:
> JSONField may also be a non-object/primitive [#1095](https://github.com/tfranzel/drf-spectacular/issues/1095)

We have experienced a change in generation, losing our object specification:
![image](https://github.com/tfranzel/drf-spectacular/assets/12081940/ac9136a1-1a64-4568-aac5-63125f93899d)

I understand that if it is indicated as a dictionary by default, it could be considered an object.

So the solution in my situation would be to add this:
> @extend_schema_field(OpenApiTypes.OBJECT)

or maybe 

> @extend_schema_field(DictField)

But I would have to do it in all my serializers.

Is there any way to maintain the old behavior without having to change all our serializers?

**To Reproduce**

Set a JSONField with default=dict

**Expected behavior**

Keep object when jsonfield is an object.

**Comment by tfranzel** [comment]
Hi, that is much appreciated. So the new behavior is more correct that the old one because the user rightfully pointed out that `"some string"`, `[1,2,3]`, `13` are also valid contents for a JSONField and thus we had to drop the dict assumption.

However if you only use dicts, you can customize global mapping with this extension:

```python
class RestrictedJsonFieldExtension(OpenApiSerializerFieldExtension):
    target_class = "rest_framework.fields.JSONField"
    # match_subclasses = True  # not needed here but good to know.

    def map_serializer_field(self, auto_schema, direction):
        return build_basic_type(OpenApiTypes.OBJECT)
```

see here how to load the extension: https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-5-extensions

**Comment by SorianoMarmol** [comment]
Thanks a lot! much appreciatted
