### ISSUE TITLE
What's the relation to DRF OpenAPI schema

### ISSUE THREAD

**Issue by hnykda** [tfranzel/drf-spectacular#134]
Hey. 

Could someone explain to me how this project uses the new additions to DRF, such as https://www.django-rest-framework.org/api-guide/schemas/#generating-a-dynamic-schema-with-schemaview ? Is that entirely different or the same?

**Comment by tfranzel** [comment]
Hi! afaik the OpenAPI3 overhaul is supposed to be release with DRF 3.12. i believe this still refers to 3.11 which may look different on their current master. `drf-spectacular` was forked from their initial OpenAPI3 implementation but is now largely incompatible to it.

that means if you want to use `drf-spectacular` you have to use our dynamic schema, UI facilites because they differ. usage may look very similar but the underlying implementation differs significantly. you will notice that very quickly once you try to adapt the DRF generated schema with decorators and stuff. hope that answers your question.

**Comment by hnykda** [comment]
Wohha, that's a quick response, really appreciated! Thanks! I think it could be worthwhile to mention this in the readme or some FAQ. Thanks for a great work!
