### ISSUE TITLE
component properties description support

### ISSUE THREAD

**Issue by gthieleb** [tfranzel/drf-spectacular#140]
it would be great to have a property `description` generated by its serializer `field.label` or in case of ModelSerializer its `ModelField.verbose_name` attribute.

**Comment by tfranzel** [comment]
hi @gthieleb, sry for the late reply. for field `description` we currently extract `help_text` either from the serializer field (Serializer) or model field (ModelSerializer) if it is available.

can you give an example of where `verbose_name` would be beneficial, because i imagine that it is usually used just as a nicer field name representation (e.g. `field_email` --> `Email`), in which case it would not really add additional information and make the schema a bit more noisy. but i could image having that as a fallback to `help_text`.

**Comment by gthieleb** [comment]
Hi tfranzel, thanks for your answer. 

Like you describe I always use the `verbose_name` attr for a beautiful presentation of a form field label and also manage the translation of the label.

I randomly also use `help_text` to describe a further usage of a form field. 

The main usage is to deliver this information via OpenApi spec to the frontend and avoid to maintain it in multiple places.

**Comment by gthieleb** [comment]
I'll create a pull request to include generation of the `title` property from the `verbose_name` attr as described in [json-schema generic keywords](http://json-schema.org/understanding-json-schema/reference/generic.html).

**Comment by tfranzel** [comment]
sry this fell of the waggon. i was honestly unsure where to put it initially. `title` did not come to mind, but it looks like the perfect place. i hope duplication (like `title` `description` and `summary` all being the same) won't be an issue. happy to look at a PR. thanks!
