### ISSUE TITLE
SpecacularAPIView.as_view() outputs security even when SERVE_PUBLIC is True

### ISSUE THREAD

**Issue by maximebel** [tfranzel/drf-spectacular#158]
**Describe the bug**
In the schema output, I get basicAuth and coockieAuth even if I set SERVE_PUBLIC to true. The consequence is that they appear in Redoc in the security section even if not used. I use a different authentication mechanism implemented with OpenApiAuthenticationExtension so these default security options are never used in my code.

As of now I have to write it like that SpectacularAPIView.as_view(schema=None) to prevent the default authentication to appear

**To Reproduce**
Use the provided example : path(r'schema/', SpectacularAPIView.as_view(), name='schema'),

And have a look to the generated schema

**Expected behavior**
The schema generation for SpectacularAPIView should not output security section if SERVE_PUBLIC is set

**Comment by tfranzel** [comment]
hi @maximebel, 

i'm not entirely sure this is actually a bug. i believe `SpectacularAPIView` uses the DRF setting `DEFAULT_AUTHENTICATION_CLASSES` for the auth classes. the default are the two mentioned, thus they surface in the schema, because they are used there. this is what i would expect. you could either change the DRF default setting to your custom auth class or subclass `SpectacularAPIView` to override the auth. If you did change `DEFAULT_AUTHENTICATION_CLASSES` this is indeed a bug. 

2 other remarks:

- fyi, you did use `SpectacularAPIView.as_view(schema=None)` to disable the schema endpoint in the schema. there is a dedicated setting for that: `'SERVE_INCLUDE_SCHEMA': False,`
- `SERVE_PUBLIC` has a different purpose. it is there to reduce the schema and only list endpoints your current user has access to.

**Comment by tfranzel** [comment]
since `SpectacularAPIView` has `allowAny` (`SERVE_PERMISSIONS`),  the auth classes are not even strictly necessary there. i admit this is a bit intuitive, but it is the default DRF behaviour. so you wouldn't even have to set **your** auth class there. setting an empty list on `SpectacularAPIView`  would also suffice.

**Comment by maximebel** [comment]
Hello, 

Thanks for your feedback. Actually, I think my problem is that I have no default authentication mechanism. My server can be accessed from two different portals which have their own authentication mechanism. So I have inherited GenericAPIView and have an authorization field with my two allowed methods. So I'm not using anywhere the default setting.

I think this is why SpectacularAPIView displayed the default one. I'm going to modify the code to take into account your suggestions.

Regards

**Comment by tfranzel** [comment]
i see. that makes perfect sense. you could do this

```path('schema/', SpectacularAPIView.as_view(authentication_classes=[]), name='schema'),```

to remove the unused methods from the schema (prob for the swagger/redoc views too.). you could also remove the default auths in the settings, which would make them disappear here.

i'll close this if you don't mind, because its more of a feature than a bug.
