### ISSUE TITLE
Non-blank strings emit schema that allows blanks

### ISSUE THREAD

**Issue by zefciu** [tfranzel/drf-spectacular#186]
As stated in OpenAPI3 documentation: “ Note that an empty string "" is a valid string unless minLength or pattern is specified. ”
https://swagger.io/docs/specification/data-models/data-types/#string In drf, however "" is not a valid input for fields that have `allow_blank` set to False. drf-spectacular emits a field that allows blanks even if allow_blank is set to False.

**To Reproduce**
A simple way to show this error is to create any API that contains a non-blank character field and then run schemathesis against it. Output:
```
Received a response with a status code, which is not defined in the schema: 400

Declared status codes: 200                                                                                                                                                                      

Body            : {'email': '0@A.com', 'first_name': '', 'ip_address': '', 'last_name': ''}
```

**Proposed fix**
A simple idea to fix this would be to add `minLength: 1` to all the fields that aren’t marked with `allow_blank`.
Please confirm that this would be a good solution, so I can work on a patch.

**Comment by tfranzel** [comment]
hi @zefciu, that is quite interesting and has been an oversight until now. `minLength: 1` is not only simple but probably the only way to model this here. yes, i would consider this change viable.

**Comment by tfranzel** [comment]
> This behavior is the rule, not the exception. 

@intgr totally agree. I have always brushed over this aspect. However, I would assume that the majority do use their serializers in a predictable symmetric way. Also I consider the blank thing a DRF/Django quirk that is worth pointing out more prominently in the schema.

Theoretically we could remove all "restricting" keywords from `readOnly` fields and all responses with `COMPONENT_SPLIT_REQUEST`. The question is "is it worth it"? Besides not being enforced it also has informational value. And finally in case of unpatched `ModelSerializers`, it is indeed a restriction (enforced by the database not the serializer though).

Imho there will always be some gray area due to the way DRF works. Can we gain something here by being pedantic?

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
