### ISSUE TITLE
Could not derive type of path parameter "id" but the path fragment is "pk" ?

### ISSUE THREAD

**Issue by eLvErDe** [tfranzel/drf-spectacular#194]
Hello,

Could you help me understanding why spectacular says that ?

I have the following code snippets:

```python

group_preference_multi_by_id = SelfGroupMultiPreferenceViewSet.as_view({
    "get": "retrieve",
    "put": "update",
    "delete": "destroy",
})

group_preference_urlpatterns = [
    path(
        "api/preferences/multi/by-group/<path:group>/<path:application>/<path:preference>/<int:pk>/",
        group_preference_multi_by_id,
        name="multi_preferences_by_given_group_by_id",
    ),
]
```

But the generated OpenAPI route uses "id" instead of "pk" and keep warning me that type could not be infered (and defaults to string while being actually integer).

Thanks in advance,

**Comment by tfranzel** [comment]
Hi @eLvErDe,

this is a remnant of the base implementation. `pk` is coerced to `id` by a function belonging to DRF. there is even a DRF schema settings for that:
 
https://www.django-rest-framework.org/api-guide/settings/#schema_coerce_path_pk
https://github.com/encode/django-rest-framework/blob/bb795674f86828fc5f15d6d61501cc781811e053/rest_framework/schemas/generators.py#L210
 
typing path params should always work, but due to the `pk` coercion it fails here. the code is looking for `id` (but `pk` was typed in the path). i guess this counts as a bug. 

however, this is usually not a problem as the type of `pk`/`id` is then retrieved from the model of the viewset, but i guess your `SelfGroupMultiPreferenceViewSet` is not a `ModelViewSet` or even a `GenericAPIView`.

**Comment by tfranzel** [comment]
@eLvErDe does this fix work for you?

**Comment by eLvErDe** [comment]
@tfranzel  Can you wait until thursday ?

**Comment by tfranzel** [comment]
normally yes but the fix is on master and i need to do a fast minor release, due to an unrelated bug in swagger ui. would be much appreciated if you could check it beforehand.

**Comment by eLvErDe** [comment]
Ok, give me half an hour

**Comment by eLvErDe** [comment]
Yes it works for me, warning is gone, path parameter is typed as integer and API is still working, so I guess your patch is OK, thanks :-)

**Comment by tfranzel** [comment]
thanks so much for doing it so quickly! release will happen very soon.
