### ISSUE TITLE
Nullable nested serializer seems to lose object serializer connection

### ISSUE THREAD

**Issue by landoephan** [tfranzel/drf-spectacular#204]
I don't know how to describe the issue well, I can show it with a screenshot and code:
![image](https://user-images.githubusercontent.com/43780811/99728358-9c07b800-2ab9-11eb-9d83-2fd84be5d798.png)
This is the generated output. Here comes the code:
`class BaseSerializer(serializers.ModelSerializer):`
`address = AddressSerializer()`
`billing_address = AddressSerializer(required=False, allow_null=True)`

as you can see the AddressSerializer gets recognized in one case, but in case of allow_null=True not. When I remove the allow_null=True it works as expected.

**Comment by tfranzel** [comment]
hi. unfortunately this is expected behavior. the schema looks like this:

```yaml
address:
  $ref: '#/components/schemas/Address'
billing_address:
  allOf:
  - $ref: '#/components/schemas/Address'
  nullable: true
```
so `billing_address` is a combination, which it has to be. the `allOf` is necessary so that `nullable` is not deleted on `$ref` substitution. there is no easy solution to make it better. SwaggerUI could detect that case but it does not. from a schema perspective there is little to be done.

**Comment by landoephan** [comment]
oh okay, so there is nothing to prevent that? I'm generating models for my Frontend from this code and having some troubles at this point

**Comment by landoephan** [comment]
thanks for the fast reply though

**Comment by tfranzel** [comment]
schema wise you can't do 
```
billing_address:
  $ref: '#/components/schemas/Address'
  nullable: true
```
because nullable is wiped out by the substitution.

afaik this is a purely cosmetic issue in SwaggerUI. last i checked our generated clients (typescript) have no trouble translating this correctly. my test generated this:

```typescript
    // typescript-fetch with openapi generator 5.0.0
    address: Address;
    /**
     */
    billing_address?: Address | null;
```

if your target has problems, its probably that specific target and a potential bug in openapi-generator.

**Comment by landoephan** [comment]
thank you!
