### ISSUE TITLE
RelatedField serializer as int

### ISSUE THREAD

**Issue by MissiaL** [tfranzel/drf-spectacular#21]
In my project I use this serializer
```python
class CustomSerializer(serializers.ModelSerializer):
    uid = serializers.RelatedField()
    reply_to = serializers.RelatedField()
    text = CharField()
```
And I would like to get the `reply_to` parameter in the schema as int, but I got string

How can i do this?

It seems to me that one could add typing `int` for `reply_to` parameter
For example
```python
class CustomSerializer(serializers.ModelSerializer):
    uid = serializers.RelatedField()
    reply_to:int = serializers.RelatedField()
    text = CharField()
```

But it does not work

**Comment by tfranzel** [comment]
first of all i'm not sure what is to be expected of``RelatedField`` and if it actually supposed to be used directly.  ``PrimaryKeyRelatedField`` would follow the source and resolve to the type of the related PK. not sure what is supposed to be resolved for ``RelatedFIeld``.

if your reply_to model has a int PK that would solve it automatically. not sure from the snippet if that is what you are after.

type hints are only supported for functions at the moment ( -> int)

otherwise you can always do a ``SerializerMethodField`` and annotate/type hint the ``get_*`` function. that should work any time.

**Comment by MissiaL** [comment]
Thank you for help! Now it works correctly!
