### ISSUE TITLE
Unable to modify defined summary

### ISSUE THREAD

**Issue by HansAarneLiblik** [tfranzel/drf-spectacular#216]
If my `function-based view` is decorated like
```py
@extend_schema(
    summary="Data function to make things",
)
@api_view(["GET"])
def data_func(request: Request) -> Response:
    pass
```

I'm unable to modify/update this `summary` in my `Schema`
```py
class Schema(AutoSchema):

    def get_summary(self) -> Optional[str]:
        summary: Optional[str] = super().get_summary()

        if getattr(self.view, "stable_api", False):
            stability = "STABLE"
        else:
            stability = "EXPERIMENTAL"

        summary = ", ".join(filter(None, [summary, stability]))

        return summary
```

because this is not called when `summary` is already defined. There is no easy way for me to customize this either, since it belongs to `extend_schema` decorator

**Comment by tfranzel** [comment]
these are the mechanics that made the most sense. for most cases "either use the default or overwrite" is doing the right thing. something in between is tricky. `get_summary()` would not be well defined in the presence of an override.

if you could live with `desciption` instead of `summary` you could do this:

```python
@api_view(["GET"])
def data_func(request: Request) -> Response:
    """ Data function to make things """
    pass
```
and override `get_description()` with the body of your `get_summary()`
