### ISSUE TITLE
Simple JWT integration goes wrong.

### ISSUE THREAD

**Issue by dem214** [tfranzel/drf-spectacular#232]
**Describe the bug**
Generated schema shows wrong response schema of `rest_fremework_simplejwt.views.TokenObtainPairView()`
![Screenshot_20201214_172547](https://user-images.githubusercontent.com/23364591/102092990-b3745f80-3e31-11eb-891b-5a841cc1eeae.png)

**To Reproduce**
Add this to urls of new django project:
```python
from rest_framework_simplejwt.views import TokenObtainPairView

urlpatterns += [path("api/token/", TokenObtainPairView.as_view(), name='token_obtain_pair'),]
```
Check the schema.

**Expected behavior**
`api/token/` view must response with schema like `{"access":string,"refresh":string}`

**Versions**
django==3.0.10
djangorestframework==3.12.1
djangorestframework-simplejwt==4.4.0
drf-spectacular==0.11.1

**See also**
Same problem can be with `from rest_framework_simplejwt.views.TokenRefreshView`

**Comment by tfranzel** [comment]
Hi @dem214, djangorestframework-simplejwt has a weird way of constructing those serializers. this should solve it.

**Comment by marcinjosinski** [comment]
Hello,
@tfranzel  this fix resolves all problems except `token/refresh` view.

Something like that resolves `token/refresh` view too.
```py
class SimpleJWTTokenRefreshView(OpenApiViewExtension):
    target_class = 'rest_framework_simplejwt.views.TokenRefreshView'

    def view_replacement(self):
        if getattr(settings, 'SIMPLE_JWT', {}).get('ROTATE_REFRESH_TOKENS', False):
            class TokenRefreshResponseSerializer(serializers.Serializer):
                access = serializers.CharField()
                refresh = serializers.CharField()
        else:
            class TokenRefreshResponseSerializer(serializers.Serializer):
                access = serializers.CharField()

        class Fixed(self.target_class):
            @extend_schema(responses=TokenRefreshResponseSerializer)
            def post(self, request, *args, **kwargs):
                pass  # pragma: no cover

        return Fixed
```

@tfranzel By the way, thanks for maintaining such a great project!

**Comment by dem214** [comment]
Nicely done

**Comment by tfranzel** [comment]
hey @marcinjosinski, i missed that one too. slightly modified your proposal to target `TokenRefreshSerializer` instead of the view. 

```python
            class TokenRefreshResponseSerializer(serializers.Serializer):
                access = serializers.CharField()
```

i think your proposal has a slight bug. as far as i understand, for `ROTATE_REFRESH_TOKENS=False` the serializer has `refresh` (request only) and `access` (response only). can you confirm this is now correct?

this also fixes `dj_rest_auth` as it optionally uses simple JWT. yeah!

**Comment by marcinjosinski** [comment]
My proposal gives the same results because I override responses here only, but targeting the Serializer is a more elegant solution.

I've just checked it and everything looks good. Thanks!

**Comment by devraj** [comment]
Was this ever resolved as part of a SimpleJWT release or do we still have to provide our own wrappers? 


Thanks for any insights.

**Comment by devraj** [comment]
While this is resolved, I noticed that the the request and response for the token endpoint uses the same model with `writeOnly` and `readOnly` attributes to denote what's to be used for the request and response.

I am using the endpoints with [`swift-openapi-generator`](https://github.com/apple/swift-openapi-generator) which didn't distinguish the attributes for requests and responses. Because the actual endpoint does the right thing I could get away with sending blank value for `username` and `password` to satisfy the initialisation of the Input parameters. However the response parsing would still fail (this as of `swift-openapi-generator==1.9.0`).

I ended up defining a couple of serializers to annotate a subclass of `TokenObtainPairView`

```python
from rest_framework import serializers

class TokenObtainRequestSerializer(serializers.Serializer):
    username = serializers.CharField()
    password = serializers.CharField()

class TokenObtainResponseSerializer(serializers.Serializer):
    access = serializers.CharField()
    refresh = serializers.CharField()
```
and then subclassed `TokenObtainView` as following:
```python
""" Annotated versions of the TokenObtainPairView for JWT authentication.

Note: that these use serializers to explicitly separate the request and 
response. The original response has the username, password, access, refresh
fields with username and password annotated for write only and access,
refresh for read only.

Generators like swift-openapi-generator end up generating a single
model for the request and response, and thus failing to parse the response.

Note that the changes are only reflected in the schema, there are no
changes to the behavior of the view itself.
"""
from drf_spectacular.utils import extend_schema
from rest_framework_simplejwt.views import TokenObtainPairView
from api.serializers.authentication import (
    TokenObtainRequestSerializer,
    TokenObtainResponseSerializer,
)

@extend_schema(
    request=TokenObtainRequestSerializer,
    responses=TokenObtainResponseSerializer,
    tags=["authentication"]
)
class AnnotatedTokenObtainPairView(TokenObtainPairView):
    """
    Custom view for obtaining JWT tokens with additional schema annotations.
    """
    pass
```

This makes `swift-openapi-generator` behaved properly and so far as I call tell should forward compatible.

I intend to use the same endpoint with [fabrikt](https://github.com/cjbooms/fabrikt) on Android, I will post on this thread if I find something particular to it.

Hopefully this helps someone else using a code generator.
