### ISSUE TITLE
path versioning issue

### ISSUE THREAD

**Issue by warnabas** [tfranzel/drf-spectacular#253]
I have three paths
api - legacy
api/v1 - v1
api/v2 -v2
when I make 
```
path(
    "docs/private/download/v1",
    SpectacularAPIView.as_view(api_version="v1"),
    name="schema_v1",
),
```
and after this 
```
path(
    "docs/private/download/v1",
    SpectacularAPIView.as_view(api_version="v2"),
    name="schema_v2",
),
```
```
path(
    "docs/private",
    SpectacularSwaggerView.as_view(url_name="schema_v2"),
    name="swagger-ui",
),
```
It writes that there is no schema_v2(and swagger has all of api's in `api` section legacy, v1, v2).
I wanted SpectacularSwaggerView to make section on each of legacy, v1, v2. but from reading docs didn't get it. appreciate your help.

**Comment by warnabas** [comment]
do you actually accept routers in urlspatterns?
```router.register("projects", views.ProjectsViewSet, basename="project")```
it's seems not to be seen by spectacular

**Comment by tfranzel** [comment]
please have a look here: https://github.com/tfranzel/drf-spectacular/blob/bffe6248ced487da2123c78468188358acdf714f/tests/test_versioning.py#L150

> It writes that there is no schema_v2

i suspect that is because `reverse` cannot find it due one of `SpectacularAPIView` or `SpectacularSwaggerView` having a `versioning_class` and not both (or none). remember what `DEFAULT_VERSIONING_CLASS` has.

i think you do the same as the tests :
```python
    path('api/schema/', SpectacularAPIView.as_view()),
    # manually versioned schema view that is in itself unversioned
    path('api/schema-v2/', SpectacularAPIView.as_view(api_version='v2')),
```
which are (in this case) unversioned views in itself. make sure they have no versioning class from `DEFAULT_VERSIONING_CLASS`!
pretty sure this should work as it is heavily tested.

**Comment by tfranzel** [comment]
issue looks stale, closing for now. feel free to comment again
