### ISSUE TITLE
add description for Tags Grouping 

### ISSUE THREAD

**Issue by A-Iskakov** [tfranzel/drf-spectacular#273]
**Describe the bug**
Docstrings from APIViews or ViewSets are not used as descriptions for the global tagging.
https://swagger.io/docs/specification/grouping-operations-with-tags/

as I understand the only possible way to describe global tags is to set TAGS in SPECTACULAR_SETTINGS

Is it possible to add docstring extraction from APIViews or ViewSets to use it as a global tag description?

**Comment by HansAarneLiblik** [comment]
We've done it in post-processing hooks, because a tag might consist of multiple ViewSets

```py
def add_app_apidocs(result: PostProcessingHookResult, **kwargs) -> PostProcessingHookResult:
    """
    Adds apidoc for defined tags
    """

    tag_descriptions = {"my_special_tag": MY_SPECIAL_TAG_DOC}

    tags: Set[str] = set()
    for path_operations in result["paths"].values():
        for operation in path_operations.values():
            tags.update(operation["tags"])

    # Map all tags to objects, add description where needed
    result["tags"] = [{"name": tag, "description": tag_descriptions.get(tag, "")} for tag in sorted(tags)]

    return result
```

**Comment by tfranzel** [comment]
no its not possible, because its does not match the OpenAPI structure. tags can be documented via `TAGS` setting (top level tags section in schema). tag extraction/estimation is part of view parsing (operations). 

@A-Iskakov this is on purpose because providing a tag with doc while view parsing could lead to conflicts with different docstrings for one and the same tag. 

@HansAarneLiblik i see what you are doing there, but the benefit is rather small imho. you still have to maintain the ``tag_descriptions`` which makes it a manual task. then you can also maintain the ``TAGS`` setting (with name/description dicts), which which is the same end result or am i missing something? i'm still missing what this postproc hook brings to the table.

**Comment by HansAarneLiblik** [comment]
You're right, using `TAGS` is pretty neat! 

But this hook also orders our tags, otherwise we have to manually order them and keep them up to date (since only some of them have global description)

**Comment by tfranzel** [comment]
@HansAarneLiblik awesome! glad that this works for you. post/pre-processing hooks are super generic on purpose. i would have never come up with that specific use-case myself. :smile: 

i think the core code should be good enough as it is right now, as the `TAGS` setting will probably cover most common user needs.

**Comment by A-Iskakov** [comment]
In my case, I decided to use a router registry to extract tags
```
  TAGS = []
  for global_tag, view_class, url_name in router.registry:
     TAGS.append({'name': global_tag, 'description': view_class.__doc__.strip()})
  with open(f'{settings.BASE_DIR}/utils/tags.pickle', 'wb') as tags_dump:
     pickle.dump(TAGS, tags_dump, pickle.HIGHEST_PROTOCOL)
```
then extract them in settings.py
```
try:
    with open(f'{BASE_DIR}/utils/tags.pickle', 'rb') as tags_dump:
        TAGS = pickle.load(tags_dump)
except FileNotFoundError:
    TAGS = []

...
SPECTACULAR_SETTINGS = {
...
 'TAGS': TAGS,
...
}
```

**Comment by tfranzel** [comment]
@A-Iskakov, ahh i see. again at the end, you are responsible for providing the needed consistency there. 

i'll close this issue, as we have no good structured/robust way of providing this, except for the already existing mechanisms (`TAGS`).
