### ISSUE TITLE
django.db.models.SlugField

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#32]
I am seeing

> could not resolve model field "catalogue.ProductClass.slug" due to missing mapping.either your field is custom and not based on a known subclasses or we missed something. let us know.

I havent determined which class it is, but both are derived from `django.db.models.SlugField`, which drf-spectacular might need a specialised handler for.

https://github.com/django-oscar/django-oscar/blob/2.0.4/src/oscar/models/fields/slugfield.py

or 

https://github.com/django-oscar/django-oscar/blob/2.0.4/src/oscar/models/fields/autoslugfield.py

**Comment by tfranzel** [comment]
actually ``models.SlugField``is already supported. derived model fields are not yet picked up though. 

i'll have to think about this because it has trade-offs. there needs to be some kind of closest match logic because a lot of fields are derived from each other. currently we only do exact class matches.

but at least the warning is misleading as it does not look for ``subclasses``.

**Comment by tfranzel** [comment]
this should also be resolved by 6c537e8 

@jayvdb please confirm that the warning has disappeared

**Comment by jayvdb** [comment]
Sorry I am not sure that I am seeing this before or after.

Maybe this is because that slug field error was being hidden behind those fixes you gave me in the gist, and I would rather not undo those atm ;-)

Related to your commit there, I am now seeing a different error for breadcrumbs.

```
could not derive type of path parameter "breadcrumbs" because model "<class 'oscar.apps.catalogue.models.Category'>" did contain no such field. consider annotating parameter with @extend_schema. defaulting to "string".
```

I guess that comes from:

```
oscarapi/urls.py:        "^categories/(?P<breadcrumbs>.*)/$",
```

And IMO it feels like the new warning is appropriate.  It is easy to fix upstream in oscarapi.  I intend to do a batch of them once we've removed the majority of the ones which can be solved in the generator.

I'm going to close this now, as I am guessing it is fixed based on my reading of that commit.

**Comment by tfranzel** [comment]
awesome, i guess :smile:  since i only have the oscar toy example, i did not encounter this myself.

i myself encountered the `breadcrumbs` only once with https://gist.github.com/tfranzel/c29f6b79967c6d4b89b78e779e2a798f#file-django_oscar_api_schema_fixes-py-L57

some of those are indeed easily fixable upstream. i suspect it comes from the oscarapi admin. in the meantime this could do maybe:
```python
class Fix11(Fix5):
    target_class = 'oscarapi.views.admin.product.CategoryList'
```
