### ISSUE TITLE
jsonschema could be an optional dependency

### ISSUE THREAD

**Issue by apollo13** [tfranzel/drf-spectacular#347]
**Describe the bug**
jsonschema is currently a required dependency; it would be nice if it could be made optional since it is only required for validation. Given that there is already a rather long list of optional deps (https://github.com/tfranzel/drf-spectacular/blob/master/requirements/optionals.txt) I think jsonschema would be a good candidate there as well.

If you are okay with making it optional I'd prepare a PR.

**Comment by tfranzel** [comment]
is there a specific reason for this request or what would we gain from this?

https://github.com/tfranzel/drf-spectacular/blob/master/requirements/base.txt are the actual dependencies. drf-spectacular depends "only" on 4 additional packages. a lot of users use the validation in their CI build chain and I consider validating the generated schema an important base functionality, which is why schema validation runs on every unit test. 

drf-spectacular (62.9 kB):
- uritemplate (15kB) : very small & required
- inflection (10kB): very small & required
- PyYAML (+~250kB): not so small and not really required but yaml is most commonly used
- jsonschema (56kB): not small, not big, not strictly required but very helpful

furthermore, bracketed pypi installs are cumbersome and a lot of people would trip over this. it has its place, but not for such a trivial case imho.

the `optional.txt` is for running the tests with all supported contrib packages. those are not installed via pypi nor are they pypi listed optionals.

**Comment by apollo13** [comment]
My main reason for the request was that jsonschema has further dependencies which have c code and no wheels -- granted I could try to add wheelsupport there. Either way I usually prefer to keep dependencies down in prod deployments, so that was also part of the reasoning. That said I fully understand your position. I'll see if I'll find time to add wheels to pyrsistent instead

**Comment by tfranzel** [comment]
i see and totally understand. i can see our sec-ops guy nodding in the background. :smile: i would prefer if you solve this upstream. what i could imagine is a bracketed install like `drf-spectacular[novalidate]` however, i would have to look this up in more detail. the default install case must remain as it is.

**Comment by apollo13** [comment]
Don't look it up, novalidate will not work. To the best of my knowledge you can only add packages with extras and not remove them. Would be great if I were wrong though.

**Comment by tfranzel** [comment]
that's a bummer :disappointed: ... that would only leave the upstream wheels solution. sorry about that.

**Comment by apollo13** [comment]
No worries, thank you for your work on drf-spectacular!
