### ISSUE TITLE
Serializer cannot use PrimaryKeyRelatedField when instance of drf serializer.Serializer

### ISSUE THREAD

**Issue by tylerblox** [tfranzel/drf-spectacular#353]
**Describe the bug**
using a PrimaryKeyRelatedField with read_only=True in a serializer inheriting from serializer.Serializer returns an error:

/drf_spectacular/openapi.py", line 508, in _map_serializer_field
    model = field.parent.Meta.model
AttributeError: X Serializer object has no attribute 'Meta'

**To Reproduce**
Non Model Serializer with a PrimaryKeyRelatedField without a queryset (read_only) in my case it's a create serializer.

**Expected behavior**
It should not require a meta and a model when on a non model serializer.

**Comment by tfranzel** [comment]
hi @tylerblox, i see. thing is that `PrimaryKeyRelatedField` usually only makes sense in combination with a model. spectacular is unable to infer the field type here as there is none. 

it would work for more specific fields like: `HyperlinkedIdentityField, HyperlinkedRelatedField, SlugRelatedField, StringRelatedField,` 

could you provide a working example on how to use a `PrimaryKeyRelatedField` on a non-model serializer in a way that makes sense?  

> It should not require a meta and a model when on a non model serializer.

not that easy actually. where should the field type then come from? a fallback on `string` is all i can see at the moment.

**Comment by tylerblox** [comment]
Fair, I guess considering my limited usage in select serializers I'll go with this, thanks.

**Comment by aehlke** [comment]
Same use case, same unexpected surprise from this. Is there a faster way users of this lib can discover this behavior/disclaimer?

**Comment by tfranzel** [comment]
@aehlke, ok so I had another look at this. 

```python
    # illegal with DRF. will throw inside DRF's meta class when the interpreter encounters it
    class XSerializer(serializers.Serializer):
        pk_field = serializers.PrimaryKeyRelatedField()

    # DRF will accept this
    class XSerializer(serializers.Serializer):
        pk_field = serializers.PrimaryKeyRelatedField(read_only=True)

```

With that said, we should not throw when encountering a construction legal by DRF. However, it is not a slam dunk. 

>  PrimaryKeyRelatedField is as valid as an integer field on a model for use in a Serializer

`PrimaryKeyRelatedField` may be an integer but it does not have to be. If the PK is a uuid, it would be wrong. Also `PrimaryKeyRelatedField` is derived from `RelatedField` and in no way shape or form related to `IntegerField`. It only becomes an `IntegerField` on the fly when there is a connection to a model with an integer pk. We could emit a warning and default to something (instead of bailing), but the fact that the field is under-specified in absence of a model/queryset will not go away imho.

> In fact Serializer exists in part because I suggested to DRF author way back in its nascence that he separate data modeling from API resource modeling

Yeah sure, and that is true for all other fields. But this one is kind of special in that regard, due to the above mentioned fact that `PrimaryKeyRelatedField` is not a "completely finalized" on its own.

**Comment by aehlke** [comment]
Thanks for digging into the details! I understand better now why it's special

**Comment by tfranzel** [comment]
as promised this should fix the error. Now a descriptive warning is emitted instead of throwing an exception.

**Comment by aehlke** [comment]
very nice
