### ISSUE TITLE
[Q] All versions in same schema

### ISSUE THREAD

**Issue by abreumatheus** [tfranzel/drf-spectacular#367]
Is there a way to show all version in the same schema?

I have just two endpointa in v2, and wanted them to be in the same schema as the v1 endpoints.

**Comment by tfranzel** [comment]
there is currently no way to do this, as we would not be able to guarantee consistency (e.g. different serializer fields). its hard to detect whether multiple versions can be safely thrown together.

**Comment by abreumatheus** [comment]
I understand. In the end i overrided the `parse` method in `SchemaGenerator` and it worked like i intended.

**Comment by abreumatheus** [comment]
@tfranzel Another question (so i don't open another issue). I user django-oidc-provider, and the token view subclasses django's `View`. Is there a way of showing this view in the schema?

**Comment by tfranzel** [comment]
> I understand. In the end i overrided the parse method in SchemaGenerator and it worked like i intended.

awesome, glad it works for you! i would prefer not to include that a feature unless requested by more people. it could break the schema in subtle ways that are hard to understand.  however i'm not ruling out that there is a more intelligent way to prevent/warn about that.

> Is there a way of showing this view in the schema?

looks like no. the views are either templated or standard django views. we rely on the DRF's base classes for views and serializers. Generally we support replacing views with corrected/mocked views via extensions, but swapping out a non-DRF view with a DRF view has not been requested yet. currently the replacement only happens after the views get rejected due to their non-DRF nature. could be done.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Comment by AndersJensenBikemap** [comment]
Our team has the same needs as request in this ticket:

We would like to have one schema, but with endpoints in different versions e.g.

​/api​/v5​/someendpoint​/

​/api​/v3/someotherendpoint​/

​/api​/v4/somethirdendpoint​/

**Comment by tfranzel** [comment]
this is more recently related to #420 . 

@AndersJensenBikemap your request is certainly reasonable but it has not come up that often before. are your endpoints serviced by differently named serializers? i don't see problems with collisions for operation paths, but i'm unsure about serializers and enums. it's tricky to prevent collisions here.

**Comment by AndersJensenBikemap** [comment]
Differently named serializers ? Maybe i am misunderstanding you, but wouldn't it be odd if the endpoints did not have different serializers ? In our system TheCoolViewset uses serializer TheCoolSerializer and ThatOtherCoolViewset uses ThatOtherCoolSerializer. So each endpoint will have its own serializer. 
Is that what you meant wih differently named serializers ?

And the challenge we face is that DRF spectacular seems to be built so that you request an API in a certain version. But our API has different versions for different endpoints. Some endpoints might be in version v3 while others might be in v5. This is because we chose to not force all endpoints to get a new version if they didn't have any changes. Only the endpoints with changes would be part of the new version.
