### ISSUE TITLE
Compatibility with DynamicFieldsModelSerializer

### ISSUE THREAD

**Issue by AlexChalk** [tfranzel/drf-spectacular#375]
**Describe the bug**
Django Rest Framework suggests using a `DynamicFieldsModelSerializer` if you want to dynamically limit the fields on your serializer at runtime: https://www.django-rest-framework.org/api-guide/serializers/#dynamically-modifying-fields. 

The default behaviour of this pattern is that all fields are available, but drf_spectacular's introspection doesn't seem to find them when one of these serializers is declared as a `serializer_class`.

**To Reproduce**
Something like this:
```
class UserSerializer(DynamicFieldsModelSerializer):
    class Meta:
        model = User
        fields = [
            "id",
            "firstName",
            "lastName",
            "email",
            "profile_image",
            "is_active",
            "phone",
        ]

class UserViewSet(viewsets.ModelViewSet):
    serializer_class = UserSerializer
```

**Expected behavior**
`drf_spectacular` interprets fields as if they were fields on a `serializers.ModelSerializer` by default, i.e. it includes them all, when a `DynamicFieldsModelSerializer` is used as a `serializer_class`. 

Thanks for all your work on this; I'm happy to try and contribute a solution with guidance!

**Comment by tfranzel** [comment]
hi! from your description i cannot really tell what is actually going wrong. are there fields missing, all of them?

i quickly compiled a test and this looks good to me. spectacular inits the serializer without params and thus nothing is filtered. seems like that is what you expected and that is what i am observing here.

```python
def test_dynamic_models():
    class User(models.Model):
        email = models.EmailField()
        is_active = models.BooleanField()
        phone = models.CharField(max_length=20)
        first = models.CharField(max_length=20)

    class DynamicFieldsModelSerializer(serializers.ModelSerializer):
        """
        A ModelSerializer that takes an additional `fields` argument that
        controls which fields should be displayed.
        """

        def __init__(self, *args, **kwargs):
            # Don't pass the 'fields' arg up to the superclass
            fields = kwargs.pop('fields', None)

            # Instantiate the superclass normally
            super(DynamicFieldsModelSerializer, self).__init__(*args, **kwargs)

            if fields is not None:
                # Drop any fields that are not specified in the `fields` argument.
                allowed = set(fields)
                existing = set(self.fields)
                for field_name in existing - allowed:
                    self.fields.pop(field_name)

    class UserSerializer(DynamicFieldsModelSerializer):
        class Meta:
            model = User
            fields = [
                "id",
                "first",
                "email",
                "is_active",
                "phone",
            ]

    class UserViewSet(viewsets.ModelViewSet):
        serializer_class = UserSerializer
        queryset = User.objects.none()

    schema = generate_schema('x/', UserViewSet)
    user_schema = schema['components']['schemas']['User']
    assert len(user_schema['properties']) == 5

```

from the generated schema:
```python
{
  'type': 'object',
  'description': 'A ModelSerializer that takes an additional `fields` argument that\ncontrols which fields should be displayed.',
  'properties': {
    'id': {'type': 'integer', 'readOnly': True},
    'first': {'type': 'string', 'maxLength': 20},
    'email': {'type': 'string', 'format': 'email', 'maxLength': 254},
    'is_active': {'type': 'boolean'},
    'phone': {'type': 'string', 'maxLength': 20}
  },
  'required': ['email', 'first', 'id', 'is_active', 'phone']
}
```

**Comment by AlexChalk** [comment]
Hi, sorry about that! 

There are fields missing, but only some of them. I have 15 declared but spectacular only finds 5. 

I don't see anything distinctive about the 10 that are missing unfortunately. The reason I suspect `DynamicFieldsModelSerializer` is that modifying the serializer to inherit from `serializers.ModelSerializer` instead makes the issue go away.

I guess I need a better repro to move this forward, but I can't straight-up share my company's source code. Do you have any suggestions on how I could try to better isolate the issue?

**Comment by tfranzel** [comment]
i'm not aware of any common issues similar to this. 

well the doc example is based on `ModelSerializer`. There are small differences between them and regular `Serializer`. that may be the cause. i adapted the test for `Serializer` as base class and it still works fine. generally we have a very good test coverage for both cases as well as all known field variations. don't know where else to look.

its hard to help here without a proper reproduction. can you modify my test to provoke the issue? all i can tell you is that this sounds very strange and is most likely produced by some undisclosed magic on your side. Where there some warnings/errors in the console/logs?

**Comment by AlexChalk** [comment]
Sorry for the late reply, I'm going to try and modify the tests to get a repro this week.

**Comment by AlexChalk** [comment]
Ok, going to close this as I can no longer repro; I guess I was making a mistake I've since fixed. Thanks for your time!

**Comment by AlexChalk** [comment]
@tfranzel reopening, apologies for the back and forth.

The issue seems to occur when the `fields` functionality is used. It looks like spectacular uses the first `fields` selection it finds for all places where the serializer is called. 

In my production code, this manifests as some properties being missing where I'd expect them to be included.

Here is a rough test that repros the opposite behaviour, but the same issue (some properties are included where you'd expect them to be missing): https://github.com/AlexChalk/drf-spectacular/blob/4d898aa6dca96114a81ce07dff1c81453395704f/tests/test_dynamic_models.py

Happy to submit a PR for this if you consider it a bug, but as I'm new to the codebase, I would appreciate some brief suggestions on where to make the change!

**Comment by tfranzel** [comment]
hey, no worries. just to mange your expectations, i'm working through the list based on severity. since this more on the "esoteric" side, it will take a moment for me to get to it. 

of course this will be a lot faster if you do a PR or at least trace the offending code location. sry that i can't give any suggestions as i have yet no idea what the underlying problem is.

**Comment by Eshaan7** [comment]
I believe the issue (https://github.com/rsinger86/drf-flex-fields/issues/73) is related.

**Comment by tfranzel** [comment]
yes that looks like the same problem. thanks for the cross-reference

**Comment by ysung6** [comment]
https://github.com/tfranzel/drf-spectacular/blob/b35b4bf0964d396677b5f9cc06be643c141343f1/drf_spectacular/openapi.py#L1210

**Comment by ysung6** [comment]
It's possibly because the `ResovledComponent`  for the serializer is being reused here.
https://github.com/tfranzel/drf-spectacular/blob/b35b4bf0964d396677b5f9cc06be643c141343f1/drf_spectacular/openapi.py#L1211

A workaround that I used was to override the `_get_serializer_name()` in the `AutoSchema` class. 
If you generate different keys for different serializer instances, the registry will not use the same key for different serializer instances.

**Comment by mschoettle** [comment]
I think this is the case. Just ran into this as well where the fields that are used in the first occurrence of the serializer are shown in all other occurrences.

```py
user = UserSerializer(fields=['name'])
user2 = UserSerializer(fields=['name', 'email'])
```
would show only `name` in both cases.

**Comment by tfranzel** [comment]
@mschoettle looking at your example, I see two core issues:

1. We assume a serializer is more or less static by default. So reusing the component, when the `UserSerializer` class is encountered again, is currently expected behavior. This might be addressable with a `OpenApiSerializerExtension` (the portable version of what @ysung6 was doing)
2. We only have one component name available there (`User`). If we encounter the `user2` field, which name should be used for that component? Suffixes would be a possible but awkward solution. Using the field name is also not optimal as you might reuse that serializer configuration under different field names, and then we would not be able to guess which one is desired.

Imho the lack of information in issue 2 is the blocker here.

**Comment by tfranzel** [comment]
This is not really a fix per se but an explanation/example on how to mitigate this. Since we cannot resolve the name nicely (without hash/numeral suffixes), we require a bit more input from the user. I added a test that outlines this in detail. 

Please refer to [24b8a98](https://github.com/tfranzel/drf-spectacular/commit/24b8a9890d59900d102490a48e286d08cdcc7ab5) for a complete and working example on how to resolve  this issue.

1. Adapt `DynamicFieldsModelSerializer` to take a `ref_name` argument. 
2. add a `DynamicFieldsModelSerializerExtension` that uses the `ref_name` in schema generation.
3. use it, e.g. `UserSerializer(fields=['id'], ref_name='CompactUser')` 
    Use a fresh name for each unique `fields` argument to prevent collisions.
