### ISSUE TITLE
Unable to change media_type for response in @extend_schema_serializer

### ISSUE THREAD

**Issue by Arka-cell** [tfranzel/drf-spectacular#380]
The following serializer is expected to take a file upload and return a file. I extended its schema as follows:

```python
@extend_schema_serializer(
    examples=[
        OpenApiExample(
            "File only",
            summary="Update/Upload File with PUT method",
            description="Upload authenticated Seeker's CV",
            value="cv_file.pdf",
            media_type='application/pdf',
            request_only=False,
            response_only=False
        ),
    ],
)
class CvFileSerializer(serializers.ModelSerializer):
    class Meta:
        model = CV
        fields = ["cv_file"]
```

Requests are customized as I want in accordance with APIView I've made, but the GET Response shows JSON format the same as the serializer:

```json
Content type
application/json
{
  "cv_file": "string"
}
```

Instead, I want this:

```json
Content type
application/pdf

cv_file.pdf
```

So, I can basically change the media/content type for my requests with `@extend_schema_serializer` but not my responses. How to by pass this?

**Comment by tfranzel** [comment]
hi @Arka-cell, what you did there was generally the right thing to do.

1. theoretically, the examples by itself is fine like that. 
2. the view filters out that example because it does not know about `application/pdf`

so you must also tell the view what it answers with (see examples below `extend_schema_view` `extend_schema`). but now you have a new problem

3. the `extend_schema`/`extend_schema_view` overrides the serializer and thus the examples attached to `CvFileSerializer` is not processed anymore.

for that reason i moved the example to the view annotation. you can reuse the examples by assigning them to a variable. i'm not sure if that is what you want, but the code you have provided seem not 100% correct 

sidenote: generally i'm not sure if example is even the right path to go here. you would need to put binary data into `value`, which is kind of hard to do. generally that makes sense only for human readable values. you can use description and summary also on `extend_schema` for documentation purposes.

```python
    class CvFileSerializer(serializers.ModelSerializer):
        class Meta:
            model = CV
            fields = ["cv_file"]

    cv_example = OpenApiExample(
        "File only",
        summary="Update/Upload File with PUT method",
        description="Upload authenticated Seeker's CV",
        value="BINARY DATA FOR PDF",
        media_type='application/pdf',
    )

    @extend_schema_view(
        retrieve=extend_schema(
            responses={('200', 'application/pdf'): OpenApiTypes.BINARY},
            examples=[cv_example],
        ),
        update=extend_schema(
            request={'application/pdf': OpenApiTypes.BINARY},
            responses={204: None},
            examples=[cv_example],
        ),
    )
    class XViewset(mixins.RetrieveModelMixin, viewsets.GenericViewSet):
        serializer_class = CvFileSerializer
        queryset = SimpleModel.objects.none()

        def update(self, request, *args, **kwargs):
            pass
```

**Comment by Arka-cell** [comment]
hi @tfranzel thank you for the answer! Unfortunately the code you gave me didn't work too, but it helped me to find a fix using `@extend_schema` only. Here is the code:

```python
    @extend_schema(
        responses={('200', 'application/pdf'): OpenApiTypes.BINARY},
        examples=[
            OpenApiExample(
                "CV Representation",
                summary="Representing explicit CV field",
                description="Retrieving authenticated Seeker's CV",
                value="PDF FILE BINARY DATA",
                media_type="application/pdf",
            )
        ],
    )
    def get(self, *args):
         # do something
         pass

    @extend_schema(
        responses={('200', 'application/pdf'): OpenApiTypes.BINARY},
        examples=[
            OpenApiExample(
                "CV Representation",
                summary="Representing explicit CV field",
                description="Retrieving authenticated Seeker's CV",
                value="BINARY DATA FOR PDF",
                media_type="application/pdf",
            )
        ],
    )
    def put(self, request):
        # do something
        pass
```

This works fine and changed the content type for me. Thank you!

**Comment by tfranzel** [comment]
awesome. that'll work too. you are using a APIView and not a Viewset. therefore replace `retrieve`/`update` (from my example) with `get`/`put` and it will work too. just so you know
