### ISSUE TITLE
No paths found in schema

### ISSUE THREAD

**Issue by foucdeg** [tfranzel/drf-spectacular#423]
**Describe the bug**
I tried configuring drf-spectacular according to the doc. The resulting yaml schema lists no paths.

In our previous implementation (using base DRF) we would use `rest_framework.schemas.get_schema_view` using the `patterns` argument to explicitly specify the URLs pattern to include.

We tried to use SpectacularAPIView.as_view() and could not find a way to explicitly specify the patterns.

**To Reproduce**

We simply followed the install doc.

**Expected behavior**

Either autodiscovery of endpoints, or a way to specify which endpoints to generate a schema for.

**Comment by tfranzel** [comment]
Hi @foucdeg,

this is usually because of versioning: https://drf-spectacular.readthedocs.io/en/latest/faq.html#i-get-an-empty-schema-or-endpoints-are-missing

for the view you can give an explicit version with`SpectacularAPIView.as_view(api_version='v2')`

if `SpectacularAPIView` has a `versioning_class` (via settings or explicitly) and is nested somewhere where there is a version (namespace/path) this happens automatically.

if you want to change the list of endpoints you can do `SpectacularAPIView.as_view(urlconf=urlpatterns_v1)` for example. by default all `urlpatterns` available in `urls.py` are used.

**Comment by foucdeg** [comment]
These two together worked, thanks!
