### ISSUE TITLE
Top level tags

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#43]
As mentioned in https://github.com/tfranzel/drf-spectacular/issues/41 , https://github.com/dhcode/openapi-ui displays only "untagged" for drf-spectacular schema, because it doesnt have tags at the top level.

An example with tags in the top level can be seen on
1. https://dhcode.github.io/openapi-ui/
2. Select USPTO v3
3. Notice "metadata" and "search" on the left

**Comment by jayvdb** [comment]
Tags is able to be set in https://drf-spectacular.readthedocs.io/en/latest/settings.html , however my generated schema, so it should be possible to generate a default tags which includes all the tags generated in the schema.

Also it would be helpful if there was some information about why some tags are detected and other times are not.  A code docstring says "use first non-parameter path part as tag"  Perhaps there are some extra fallbacks which create sane default tags?

**Comment by tfranzel** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields

according to spec tags are not required to be declared in the global list, but it could certainly be accomplished.

it basically does what is says: take the first path part that is not a parameter as sole tag. not sure if there is a general way to do this, because everyone has different requirements. could you elaborate on tags not detected?

**Comment by Mopsan** [comment]
How I can configure this tags for multiple subsets of the API?

**Comment by tfranzel** [comment]
@Mopsan there is no mechanism yet for that. however if you are asking for subsets can maybe already cover that with the regex e.g. `'/api/v[0-9]'`. the regex match is removed and then the above mentioned logic is applied. 

in general, it is probably advisable to extend the AutoSchema and override the tag extraction if you need something special. the AutoSchema is designed to be easily extendable like that.

unless of course there is a reasonable general approach to this. i'm open to suggestions here.

**Comment by jayvdb** [comment]
> could you elaborate on tags not detected?

I cross checked and there are no paths which didnt have a tag.

I have 122 oscarapi/ paths, and the first 39 are oscarapi/admin/ .

It would be nice to have a more advanced tag creation algorithm that detects large subpaths and creates sub-tags for those.  A threshold setting could be used to determine how large each subpath should be before it causes a sub-tag.

**Comment by tfranzel** [comment]
there is no one-size-fits-all for tags. the current solution tries to be as reasonable as possible. compatible improvement suggestions are welcome.

top level tags are not required by the OpenAPI specification and Swagger & Redoc work fine without 
them.

closing this for now because the issue is stale and there is currently no plan for this.
