### ISSUE TITLE
Operation IDs by method name for actions

### ISSUE THREAD

**Issue by tiholic** [tfranzel/drf-spectacular#439]
Operation ID & description can only be configured as a hashable value (string), this doesn't scale when we have custom actions on viewset which may support multiple methods

A random example:
```py
class NewsFeed(viewsets.GenericViewSet):

  @extend_schema(operation_id="likeFeed", description="manage likes")
  @action(detail=False, methods=['POST', 'GET', 'DELETE'])
  def likes(self, request):
    # handle like/dislike/get likes count
    ...
```

Here's a suggestion for operation specific configuration:
```py
class NewsFeed(viewsets.GenericViewSet):

  @extend_schema(operation_id={
    "POST": "likeFeed",
    "DELETE": "dislikeFeed",
    "GET": "getLikes",
  }, description={
    "POST": "like current feed",
    "DELETE": "remove like for feed",
    "GET": "get likes count for the feed",
  })
  @action(detail=False, methods=['POST', 'GET', 'DELETE'])
  def likes(self, request):
    # handle like/dislike/get likes count
    ...
```

**Comment by tfranzel** [comment]
hey @tiholic, i see. of course `extend_schema` makes little sense like that when using `operation_id` and multiple methods.

i believe your proposal is already possible in a slightly different way. `extend_schema` supports scoping and multiple decorations.

you can try the following snippet. this should work as is. have not tested your specific usage but it should work, because i'm pretty sure the tests cover this use-case.

```python
class NewsFeed(viewsets.GenericViewSet):

  @extend_schema(operation_id="likeFeed", description="xxx", methods=["POST"])
  @extend_schema(operation_id="getLikes", description="yyy", methods=["GET"])
  @extend_schema(operation_id="dislikeFeed",description="zzz", methods=["DELETE"])
  @action(detail=False, methods=['POST', 'GET', 'DELETE'])
  def likes(self, request):
    # handle like/dislike/get likes count
    ...

```

**Comment by gcampion-ionos** [comment]
This was very helpful, thanks for posting!
