### ISSUE TITLE
Is it possible to use namespaces as tags?

### ISSUE THREAD

**Issue by arielpontes** [tfranzel/drf-spectacular#446]
I'm working on a Django project with multiple apps. Currently we generate a Swagger UI based on a YAML file that uses, but we want to migrate to `drf-spectacular` so we don't have to manually update the YAML file as the API evolves. My endpoints look like like this:

```
/api/1.0/app1/endpoint1
/api/1.0/app1/endpoint2
/api/1.0/app2/endpoint1
/api/1.0/app2/endpoint2
...
```
In my `urls.py`, I have this:

```
urlpatterns = [
    path("api/1.0/", include((router.urls, "api"))),
    # ...
    # Schema
    path("schema/", SpectacularAPIView.as_view(api_version="api"), name="schema"),
    # Swagger UI:
    path(
        "swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "swagger/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
]
```

In the Swagger UI generated from the YAML, tags are used to display app1 endpoints under an app1 header, app2 under app2, etc:

```
openapi: 3.0.3

# ...

tags:
  - name: App1
    description: App1 endpoints
# ...

paths:
  /app1/endpoint1/:
    get:
      tags:
        - App1
  # ...
```

In the Swagger UI generated `drf-spectacular`, all endpoints show up in a flat list under a single header ("api"). How can I have a header with a custom description for each app? I couldn't find much info regarding tags in the docs.

**Comment by tfranzel** [comment]
since you have a slightly custom setup the automatic prefix finder will not be perfect. you would need to write a small regex that strips away `/api/1.0/app1/` so that only `endpoint1` remains.  the settings document how to use this:

https://github.com/tfranzel/drf-spectacular/blob/cd8f73c34412cf1613d7dbffed6eb6a004945af6/drf_spectacular/settings.py#L7-L12

otherwise you should make yourself familiar with `extend_schema` for all other customizations. you can also achieve this with `extend_schema`, but going with the settings would be better as you only need to one regex to make this look nice for the whole API.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Comment by arielpontes** [comment]
It worked perfectly, thank you! Sorry for the delayed response. I still have one issue though, the root of the API is not included in the list of endpoints. Any idea what I could still be doing wrong?
