### ISSUE TITLE
External yaml overlay

### ISSUE THREAD

**Issue by jayvdb** [tfranzel/drf-spectacular#45]
This is a feature request.

Rather than having lots of settings and decorators, and difficulty altering the schema for installable apps, it would be nice to be able to have an external yaml file which is overlaid(*merged*) with the generated schema.

I would be interesting in building this if acceptable to the maintainers.

**Comment by tfranzel** [comment]
of course this would kill most issues by taking out the sledgehammer. i can see how this would be the quickest path, but i'm hesitant go go down that route at this point. 

- application 1: theoretically this would be a deep merge of the `SchemaGenerator.get_schema()` output (where the data structure is still python dicts/lists). nothing special to schema generation here. 
- application 2: loading the overlay into spectacular, using it as a starting point to prevent warnings will be hard/impossible due to the way the code is structutured currently. to really integrate this, a lot would have to be refactored.

**Comment by jayvdb** [comment]
I would be going down the "application 1" path - the number of warnings do not bother me.  I see it as an overlay , not an underlay. ;-)  The objective would be 1) to get a high quality API despite drf-spectacular not being perfect yet, and 2) to have customisations/settings in a file in a more suitable file format, which can possibly even be linted with openapi linters/tools.

Also I expect I could do "application 1" approach by creating a separate wrapper app around drf-spectacular, like the many wrappers around drf and drf-swagger.

**Comment by tfranzel** [comment]
@jayvdb i introduced the last missing piece for being able to override "everything" lib related: 43411503505b3a8e17f8f896b6969ad6ca160a19

i was able to fix all issues in a vanilla `django-oscar-api` install with the 4 override mechanisms. the phonenumber thing i ignored. i created a gist for reference 
https://gist.github.com/tfranzel/c29f6b79967c6d4b89b78e779e2a798f
drop that in let me know how it is looking. 

the benefit of that approach is that those fixes are portable and can be used by anyone (in contrast to custom overlays.) we could have a registry for those libs. i wouldn't want to maintain those, but make them at least easily findable/usable.

**Comment by tfranzel** [comment]
closing this because overlay can be realized without any changes to spectacular. 

@jayvdb i did not receive any feedback on the `django-oscar-api` fixes i provided for you so i consider this resolved.

we will concentrate on the "Extension" route where fixes are portable.
