### ISSUE TITLE
Re-fetch schema, when auth token is updated

### ISSUE THREAD

**Issue by jtamm-red** [tfranzel/drf-spectacular#458]
Schema visible depends user rights. Refresh to fetch schema, when authorization is changed.

Old package 'drf-yasg' has got this feature.
`
SWAGGER_SETTINGS = {
    'REFETCH_SCHEMA_WITH_AUTH': True
}
`
https://drf-yasg.readthedocs.io/en/stable/settings.html#refetch-schema-with-auth

We need this feature.

**Comment by tfranzel** [comment]
Hi! this has come up before and we have a issue #342 for it. since we use the vanilla swagger-ui and not a old patched version of swagger-ui (as drf-yasg does), we would probably require a slightly different solution.

i'm lacking the time to implement it at the moment. any help would be appreciated.

**Comment by jtamm-red** [comment]
I did Swagger-ui issue as feature: https://github.com/swagger-api/swagger-ui/issues/7425

We have to wait until this feature completing.

**Comment by tfranzel** [comment]
please review #552

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
