### ISSUE TITLE
Defining a file upload endpoint

### ISSUE THREAD

**Issue by tiholic** [tfranzel/drf-spectacular#476]
I'm trying to define an endpoint which  is a pure file upload API and doesn't depend on a model

swagger ref: https://swagger.io/docs/specification/describing-request-body/file-upload/#multipart

Tried setting this, but seems like I'm missing something.
```py
@extend_schema(
  request={
    'multipart/form-data': { 'schema': ... }  # similar to what's in the above link
  }
)
```

**Comment by tfranzel** [comment]
hi!

i skipped this on purpose initially, because it's only well defined when used with a MIME type listing.  basic annotation (e.g. `bytes`) has been possible though:

https://github.com/tfranzel/drf-spectacular/blob/b35b4bf0964d396677b5f9cc06be643c141343f1/tests/test_extend_schema.py#L192-L199


i added this now as it is in fact a missing feature. however, it will only work for `@extend_schema(request={MIME: {SCHEMA}})` and NOT for  `@extend_schema(request={SCHEMA})`. turns out this also creates parity again with `responses=`, so it's the right thing to do.

**Comment by tiholic** [comment]
Wonderful! Thanks. It works very well.


I believe these 2 doc strings can be updated:
https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/utils.py#L230
https://github.com/tfranzel/drf-spectacular/blob/master/drf_spectacular/utils.py#L217

**Comment by tfranzel** [comment]
awesome!

good point. updated the doc strings.
