### ISSUE TITLE
Run checks on Django startup

### ISSUE THREAD

**Issue by k0t3n** [tfranzel/drf-spectacular#477]
Sometimes when working with a swagger docs I see lots of warnings about incorrect schema in the console. It would be great to run whose checks on Django startup using [checks framework](https://docs.djangoproject.com/en/3.2/topics/checks/).

**Comment by tfranzel** [comment]
Hi,

that's a very nice idea. it definitely can make sense to run these tests on startup. 

however, i'm not sure we can turn off the warning when actually retrieving the schema. there are quite a few use-cases where schema generation can be fine when generated "offline" (checks/CLI) while "online" generation (request) has warnings.

**Comment by k0t3n** [comment]
GJ!

**Comment by HansAarneLiblik** [comment]
This kinda broke our environment.

We have 2 kinds of APIs in our project - public and internal. We're using annotations to define them and handle this logic in `SchemaGenerator`. 

We've fixed all our Public APIs (hopefully) and care when drf-spectacular gives us a warning / error regarding them.

We don't really care about these errors for `Internal` APIs, since they may be in development or not properly documented, which is acceptable.

This task currently raises this exceptions for our `Internal` APIs also. We don't want to disable these for `public` APIs.

Is there any way to override with some logic, for which endpoints these checks are run ?

**Comment by tfranzel** [comment]
Hi @HansAarneLiblik, sry for the inconvienience. i fixed some bugs and added switch to turn this off, which will be released in `0.18.1` very soon. just waiting for some feedback.

this will turn off the new check. i would suggest just doing that and carrying on as you always did as nothing else changed. your special case is not really applicable here, but you can still do `./manage.py spectacular --fail-on-warn ...` as before.

```
'ENABLE_DJANGO_DEPLOY_CHECK': False
```
