### ISSUE TITLE
Unable to have some endpoints camel case and other snake case

### ISSUE THREAD

**Issue by samrensenhouse** [tfranzel/drf-spectacular#478]
I have some endpoints in my application that are not converted to camel case and others that are for compatibility reasons. As far as I can tell this is not supported, if I add this setting it changes all endpoints.
```
'POSTPROCESSING_HOOKS': ['drf_spectacular.contrib.djangorestframework_camel_case.camelize_serializer_fields']
```

I currently change the renderer and parser on the ViewSet like so:
```
class ExampleViewSet(viewsets.GenericViewSet):
    renderer_classes = (CamelCaseJSONRenderer, CamelCaseBrowsableAPIRenderer)
    parser_classes = (CamelCaseJSONParser,)
```
so that only this specific viewset is changed, while the rest use drf's default renderer and parser. It seems like drf-spectacular should respect the renderer and parser classes given by default without further customization needed. Similar libraries like drf-yasg seemed to follow this behavior as well.

**Comment by tfranzel** [comment]
> It seems like drf-spectacular should respect the renderer and parser classes given by default without further customization needed

not that easy actually :smile: the thing is renderers/parsers have no well defined interface apart from their MIME type. looks like drf-yasg does explicitly handle this library on a view level, but i cannot see the necessary code to prevent collisions like in the below scenario. 

but let me ask a practical question. what would happen if you use the same serializer in a "camel-cased" view **and** in a "regular" view? you would most likely have a conflict as there is only one serializer schema object, but the properties would be named differently depending on the view who uses it. that's trouble! we guarded against this issue by doing it on a global level (hook).

since we have a different code structure to drf-yasg, there is no easy way of adding this, except of course a hack which i prefer not to.

**Comment by tfranzel** [comment]
at his moment i don't see a way to cleanly support this request without breaking a few assumptions we make.

long story short: i would suggest copying `camelize_serializer_fields` , adapt it to your needs and register it in `POSTPROCESSING_HOOKS`.

**Comment by samrensenhouse** [comment]
Ah I can see the issues that would raise. I might check out what drf-yasg does on conflicts like that, but I don't really see any obvious answer other than auto generating some new schema object name on clash, but that doesn't seem all that great.

I looked into creating my own hooks, but from the available info it looked like I would have to hardcode strings to make that work. Not sure if this is possible, but it would be nice if the viewset used for a given api endpoint was available. I could then use the appropriate parser and renderer as I don't have clashes.
