### ISSUE TITLE
Wrong resolve serializers with similar name

### ISSUE THREAD

**Issue by mosi-kha** [tfranzel/drf-spectacular#606]
**Describe the bug**
I have two apps that each one has a separate serializer with the name `BatchSerialzier` but different attributes and imported to view on apps.
because of the similar name, swagger for both apps views resolves one of `BatchSerializer`, while they are completely different. when I changed the name of one of the serializers it's will be correctly resolved.

**Comment by tfranzel** [comment]
Hi! If a name is reused for different serializer classes, spectacular **should** emit a warning in the logs like 

```
Encountered 2 components with identical names "X" and different classes ....
```

This is expected behavior, since we cannot reliably generate good alternate names.  Either use `ref_name` on the serializer Meta class (yasg compatiblity) or annotate a alternative name on the other serializer classes.

```python
    @extend_schema_serializer(component_name='ABC')
    class OneSerializer(serializers.Serializer):
        pass
```
