### ISSUE TITLE
How to provide custom pagination fields in the payload?

### ISSUE THREAD

**Issue by MatejMijoski** [tfranzel/drf-spectacular#624]
I've added some custom pagination fields to the response but can't seem to find a way to add them to the schema. In `drf-yasg`, I did that with a Pagination Inspector, but seeing that that class doesn't exist here, is there some other class that I can override to provide these params?

**Comment by tfranzel** [comment]
Hi,

we do not have an Inspector, because we utilize the facilities that DRF provides, namely:

https://github.com/encode/django-rest-framework/blob/45082b39368729caa70534dde11b0788ef186a37/rest_framework/pagination.py#L232

you need to overload the `get_paginated_response_schema` method of your custom paginator to reflect your changes and spectacular will pick that up.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
