### ISSUE TITLE
The generation of the same application through the API and through the console gives different ways

### ISSUE THREAD

**Issue by VladislavN** [tfranzel/drf-spectacular#636]
I added swagger endpoints made a get query and got a scheme (which seems to me more correct)
Then I input in console the "python manage.py spectacular --format openapi-json --file schema.json"
And got different results, quite a bit, but they differ, the most obvious place is Retrieve endpoints with lookup_fields

Sample code
`class CombinationViewSet(viewsets.ModelViewSet):
    lookup_field = 'id'
    
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)
`

Result
![Снимок экрана от 2022-01-19 20-10-35](https://user-images.githubusercontent.com/33672258/150180275-a4497d22-700c-4e95-a8e6-50ac5709f166.png)

**Comment by tfranzel** [comment]
Hi @VladislavN,

there are cases where the schema varies between CLI and endpoint. However, those are usually due to permission and versioning features, which have to be turned on explicitly.

The difference you shown cannot result from those optional (default off) features. It seems to me you did not run the same codebase state in both versions. This happened to me when I ran the backend in docker (with an older state) and CLI outside of it. If you use docker, rebuild the container before comparison.

**Comment by VladislavN** [comment]
Thank you, you were right, I went to the container, launched a console command from there and got the same result
