### ISSUE TITLE
Make Swagger UI docs read-only

### ISSUE THREAD

**Issue by KStenK** [tfranzel/drf-spectacular#643]
Hi!

Is it possible to turn off or not show the "Authorize" and "Try out" buttons on swagger UI documentation?

I need to show API docs publicly and don't want that anyone can interact with API through the documentation page.

**Comment by tfranzel** [comment]
Hey, we only provide the schema, swagger-ui does the UI, so this is out of our jurisdiction basically.

Other have asked for this upstream: https://github.com/swagger-api/swagger-ui/issues/3725

We have a setting called `SWAGGER_UI_SETTINGS` where you inject that proposed extension. 

```python
"SWAGGER_UI_SETTINGS": """ {
  'deepLinking': true,
  'plugins': [
    function() {
      return {
        statePlugins: {
          spec: {
            wrapSelectors: {
              allowTryItOutFor: () => () => false
            }
          }
        }
      }
    }
  ]
}
"""
```

Additionally `AUTHENTICATION_WHITELIST` would need to support empty lists, which it does not at the moment. otherwise you will see the authorize button. 

Or maybe that js snippet can also be adapted to remove the `Authorize` button.
