### ISSUE TITLE
Unable to generateschema

### ISSUE THREAD

**Issue by jd-dev-pneu** [tfranzel/drf-spectacular#644]
Using djangorestframework version 3.13.1 and the current version of drf-spectacular (0.21.1), the generateschema management command no longer generates a schema.  When executing the command,

python manage.py generateschema,  the following error is encountered,

.../python3.9/site-packages/rest_framework/schemas/openapi.py", line 81 in get_schema
   operation = view.schema.get_operation(path,method)
TypeError: get_operation() missing 3 required positional arguments: 'path_prefix', 'method', and 'registry'

Verified that DEFAULT_SCHEMA in the REST_FRAMEWORK settings was set to 'drf_spectacular.openapi.AutoSchema'

I know that drf-spectacular is not certified for djangorestframework versions past 12.4.x, but would like to know when a compatible version of drf-spectacular will be released, or if this error is related to something else.

**Comment by tfranzel** [comment]
Hi,

> python manage.py generateschema,

that is DRF's own schema command. spectacular is run with `./manage.py spectacular`

> I know that drf-spectacular is not certified for djangorestframework versions past 12.4.x, 

it kind of is actually. the testsuite contains DRF master (3.13.1) which we cannot run with GH actions due to a missing feature regarding "allowed fails". we lost that canary check when we moved from TravisCI to GH Actions. locally all tests pass for me.

**Comment by jd-dev-pneu** [comment]
Ah ok, not sure how I missed that spectacular used a different generator command, but makes sense.  I guess RTFM.

Thanks,
