### ISSUE TITLE
Change ModelSerializer schema to String (in flat array)

### ISSUE THREAD

**Issue by elya5** [tfranzel/drf-spectacular#651]
**Describe the bug**
Due to having my own `to_representation` for a ModelSerializer, I want to change the OpenApi schema to only show a primary type `String` and not its own component with too many fields. However, I failed to do so.

**To Reproduce**
I have ModelSerializers along the line of:
```
class SubjectSerializer(serializers.ModelSerializer):
    class Meta:
        model = Subject
        fields = '__all__'

    def to_representation(self, instance) -> str:
        return instance.term


class TextSerializer(serializers.ModelSerializer):
    subject = SubjectSerializer(many=True)

    class Meta:
        model = Text
        fields = '__all__'
```

The API returns JSON like:
```
[{
    "title": "Text title",
    "subject": ["Subject 1", "Subject 2"]
},...]
```
However, this is not represented in the OpenAPI description of the API which assumes the whole Subject model is returned. This works automatically for a similar model with only one field, which does not require its own serializer as the result is data is returned automatically as a flat list.

For the Subject model, I tried setting `@extend_schema_fieldOpenApiTypes.STR)
` but it does not seem to work for ModelSerializers.

I have not found a way to change the generated OpenAPI from:

    Subject:
      type: object
      properties:
        code:
          type: string
          maxLength: 200
        scheme:
          type: string
          maxLength: 10
        term:
          type: string
          maxLength: 400
      required:
      - code
      - scheme
      - term
    Journal:
      type: object
      properties:
        id:
          type: string
          maxLength: 50
        subjects:
          type: array
          items:
            $ref: '#/components/schemas/Subject'
    ...

to 

    ...
        subjects:
          type: array
          items:
            type: string
    ...

Is there any way to generate the desired result?

**Comment by tfranzel** [comment]
`@extend_schema_field` will only work on regular fields or `SerializerMethodField` methods. 

Since we cannot look into `to_representation`, we assume standard behavior.

You could capture special behavior like that by writing a [OpenApiSerializerFieldExtension](https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html#drf_spectacular.extensions.OpenApiSerializerFieldExtension). 

However I would recommend refactoring `SubjectSerializer`. There are other ways of doing this without changing `to_representation`. I would override that specific field on the `SubjectSerializer` with a `SerializerMethodField` or a custom field. That way the custom behavior is more explicit and can also be discovered by spectacular. 
You could also throw away `SubjectSerializer` and instead do a custom field on `TextSerializer` (which you can then decorate).

**Comment by elya5** [comment]
Thanks for the prompt response. I am using a SerializerMethodField now :+1:
