### ISSUE TITLE
Could not resolve serpy serialzer

### ISSUE THREAD

**Issue by derneuere** [tfranzel/drf-spectacular#669]
**Describe the bug**
I have setup drf-spectacular and get the following warning:

```AlbumDateViewSet: could not resolve "<api.views.serializers_serpy.PigAlbumDateSerializer object at 0x7fc245ed6d90>" for POST /api/albums/date/. Expected either a serializer or some supported override mechanism. Defaulting to generic free-form object.```

I have defined a serpy serializer "PigAlbumDateSerializer". Are there steps I can take to get a view so that the serpy serilizer get's parsed correctly or are there other steps I should take?

**To Reproduce**
Replace a serializer_class with a serpy serializer.

**Expected behavior**
I would have expected, that the serpy serialzer gets parsed.

**Comment by tfranzel** [comment]
Hi,

serpy likely uses it's own classes for serializer and serializer fields. We are unaware of those and thus you would need to write one or more [OpenApiSerializerExtension](https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-serializer-magic-with-openapiserializerextension) and possibly also [OpenApiSerializerFieldExtension](https://drf-spectacular.readthedocs.io/en/latest/customization.html#declare-field-output-with-openapiserializerfieldextension) to tell spectacular how to handle those. 

Just fyi, the library looks unmaintained and stale since 2018 so I won't invest time in this.

**Comment by derneuere** [comment]
Thanks for the fast reply! I think this is all the information I need for now :+1:

**Comment by metamatik** [comment]
@derneuere If you don't mind me asking, did you end up writing a `drf-spectacular` extension for `serpy` or did you take a completely different path?
I'm finding myself in the same situation right now, so any experience you might be able to share would be quite helpful :)

**Comment by derneuere** [comment]
@metamatik I ended up removing serpy serializers from my code and switching to regular serializers instead. I did some testing with serpy and saw that it doesn't improve performance enough to justify maintaining a custom solution.

**Comment by metamatik** [comment]
@derneuere Thanks a lot for this quick reply 🙏🏻
