### ISSUE TITLE
Achieve oneOf schema generation for values that are not dict

### ISSUE THREAD

**Issue by rui-lomba** [tfranzel/drf-spectacular#712]
I am trying to use `PolymorphicProxySerializer` for a tricky use case that I have.

I have the following serializer:
```
@extend_schema_serializer(component_name='ExampleSerializer')
class ExampleSerializer(serializers.Serializer):
    file = serializers.ListField(child=SubmissionCreationFileField(), required=False, default=[])
```

The `file` property is a list either of UploadedFile or string, if `file` was a dictField I would know how to achieve the `oneOf` behaviour by using the following implementation on `SubmissionCreationFileField`:
```
@extend_schema_field(
    PolymorphicProxySerializer(
        component_name='SubmissionCreationFile',
        serializers=[
            FileUrlSubmissionCreationFileSerializer,
            FileUploadSubmissionCreationFileSerializer,
        ],
        resource_type_field_name=None,
    )
)
class SubmissionCreationFileField(serializers.Field):
    def to_internal_value(self, data: Any) -> Any:
        if isinstance(data, UploadedFile):
            return FileUploadSubmissionCreationFileSerializer(data).to_internal_value(data=data)

        if isinstance(data, str):
            return FileUrlSubmissionCreationFileSerializer(data).to_internal_value(data=data)

        raise ValidationError(
                f'Class {type(data).__name__} not supported as a value for submission creation file field'
            )
```

and then I would just need to declare the serializers used on the annotation.
That would work fine, however, since the values of the list are either `str` or `UploadedFile` I can't do that.

I tried to declare multiple type hints using `OpenApiTypes` on `@extend_schema_field` but that does not work.

Is there a way to do this that I was not able to see on the documentation? Or this is not supported?

**Comment by tfranzel** [comment]
Hi @rui-lomba, if i understand correctly, this is not possible at the moment. It indeed seems like a very special case. 

Plain `str` overrides are usually applied with `@extend_schema`, but since you are inside `PolymorphicProxySerializer`, you need to provide actual serializers. I believe you understood that correctly. So to go around that limitation, you tried to make that serializer present as a `str`, for which we have no mechanism on that level. 

It is not supported at the moment. I see why this could be useful to you, but I'm weary of changing the interface for this as it open up a whole list of new problems.

**Comment by rui-lomba** [comment]
Hey @tfranzel thank you for response.

What about adding support for using multiple `OpenApiTypes` on `@extend_schema_field` ?

Thank you!

**Comment by tfranzel** [comment]
although the ask is reasonable, it would add another layer to the "many" mechanics that are already quite complicated. I would refrain from adding this at this point in time, but thanks for pointing it out. If demand goes up we can certainly revisit this issue. I'll close the issue for now
