### ISSUE TITLE
Support full dict settings in custom_settings

### ISSUE THREAD

**Issue by mdefeche** [tfranzel/drf-spectacular#727]
Hello,

I have a project with several apps which can be used together or as standalone. I would like to have a separate Redoc documentation for each app with different permissions classes.

In order to achieve this, I would need to pass the following to SpectacularAPIView.as_view() 
- SERVE_URLCONF --> limit the documentation the the scope of a single or several apps (I saw list are now supported)
- SCHEMA_PATH_PREFIX --> define how tags will be identified (can already be defined)
- SERVE_PERMISSIONS --> user only has access to the right documentation 
- TAGS --> define description and extension fields (e.g. x-traitTag) related to tag objects. I want to be able to specify HTML and provide images in the description. I coudn't find a way to do this with decorators
- EXTENSIONS_ROOT --> give a different x-tagGroups to each documentation (instead of doing this in post processing hooks)

I believe most of the settings would make sense in the SpectacularAPIView so it would make sense to pass a full dict to custom_settings.

**Comment by tfranzel** [comment]
Hi,

I don't quite understand the scope of your ask. 

```python
SpectacularAPIView.as_view(custom_settings={'COMPONENT_SPLIT_REQUEST': True, ...})
```

already does allow you to change almost all settings. Due to the way the patched settings are implemented, you cannot change `SERVE_*` settings with `custom_settings`. However, that is not an issue as those settings are exposed directly in the view. The indirection of custom setting is not required there. 

```python
SpectacularAPIView.as_view(
    urlconf=...,
    permission_classes=...,
    custom_settings={'EXTENSIONS_ROOT': ..., 'TAGS': ..., 'SCHEMA_PATH_PREFIX': ...}
)
```

should be all you need. This is in line with default usage patterns of `as_view()`.

**Comment by mdefeche** [comment]
Thanks

SERVE_PERMISSIONS and SERVE_URLCONF made me forget it was doable from the view
