### ISSUE TITLE
Is there a way to mark unserializable JSON for input and output?

### ISSUE THREAD

**Issue by hmpf** [tfranzel/drf-spectacular#756]
By unserializable I mean that the input for a request can be any JSON, as long as it is valid JSON. Ditto for output (response).

Right now I've just set `request` and `responses` to `None`.

(What I actually have is that the JSON needs to fit a [JSON schema](https://json-schema.org/) which is not using   `"additionalProperties": false` anywhere: as long as one specific top object exists with a hierarchy of objects beneath it, it doesn't matter if you have additional objects anywhere, like say the entire phonebook of the planet. So the input is never 100% predictable. I extract the object and store the original input, for now.)

**Comment by hmpf** [comment]
Whoa, I found a JSON-Schema to OpenAPI converter that seems to make sensible output, but that's not the same as a drf serializer.

**Comment by tfranzel** [comment]
> Right now I've just set request and responses to None.

that is the least acceptable solution. I would do a generic placeholder object instead. `@extend_schema(request=OpenApiTypes.OBJECT` will give the generic catch all object `{'type': 'object', 'additionalProperties': {}}`


> JSON-Schema to OpenAPI converter

json schema is compatible with OpenAPI 3.1 but we are not there yet with 3.0.3. otherwise you just could have dropped in the raw jsonschema into `request=RawSchemaDictObject`.

Also note that you may write a custom OpenAPI schema object (as dict) yourself and put it into `request` or `responses`. This is a fallback mechanism if other modeling options do not work.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
