### ISSUE TITLE
Assign `explode=False` to custom DRF field

### ISSUE THREAD

**Issue by axieum** [tfranzel/drf-spectacular#757]
Hi,

I have the following custom field -

```py
from rest_framework.fields import ListField, CharField

class CSVField(ListField):
    """A character-separated values list field"""

    child = CharField()

    def __init__(self, **kwargs):
        self.separator = kwargs.pop("separator", ",")
        super().__init__(**kwargs)

```

I need to somehow mark this field so that `explode=False` and it passes as `?field=a,b,c` instead of `?field=a&field=b&field=c`

I had a look at the `@extend_schema_field()` but couldn't find a way to only specify `explode=False`?

https://github.com/tfranzel/drf-spectacular/blob/df9e115ca9b9a3ec84d60df942be28ce3cda13fa/drf_spectacular/utils.py#L478-L481

**Comment by tfranzel** [comment]
Hi,

so i'm assuming you are putting a serializer directly into `@extend_schema(parameters=[XSerializer])`. There is indeed no option for explode here since this "serializer explosion for parameters" is a special case and would not make sense for 99% of `@extend_schema_field` uses.

think of this as a convenience method so that you don't have to write down `OpenApiParameter`. However, if that is not expressive enough you need to go the regular route.

kind of said a similar thing here: https://github.com/tfranzel/drf-spectacular/issues/739#issuecomment-1140298478

**Comment by axieum** [comment]
Hi, thanks. I ended up using the manual `OpenApiParameter` to achieve this.
