### ISSUE TITLE
{format} on every endpoint, duplicate

### ISSUE THREAD

**Issue by MahmoudAljabary** [tfranzel/drf-spectacular#76]
Nice package. i'm facing the following issue:
each endpoint is duplicated in another endpoint followed by {format}. see the screenshot.
is it an issue in the package? or i'm missing something somewhere?
![Screenshot - 2020-06-05T224040 889](https://user-images.githubusercontent.com/3123672/83921089-f3210700-a77d-11ea-8aaf-ed24e921ac3c.png)

**Comment by tfranzel** [comment]
thanks! this only appears in certain circumstances and is most likely correct. probably either you or your library is using `format_suffix_patterns(urlpatterns, ...)`

https://www.django-rest-framework.org/api-guide/format-suffixes/

in those cases there must be two endpoints for a valid OpenAPI3 schema. path parameters are by definition `required=True` in the schema. since the format is optional there must be one endpoint with and one without the format.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-10

if you inspect the urlpattern you will see the duplication already happening there. if you want to prevent that, you must modify your urlpattern to exclude the format versions i'm afraid.

**Comment by MahmoudAljabary** [comment]
Yep you are right, format_suffix_patterns was the making the issue.

**Comment by lsaavedr** [comment]
@tfranzel thanks!
