### ISSUE TITLE
GenericSerializer schema override

### ISSUE THREAD

**Issue by MahmoudAljabary** [tfranzel/drf-spectacular#77]
I'm trying to implement a GenericSerializer to be used for all requests/responses and dynamically pass the required fields as needed. 
Given three methods: X, Y and Z with different schema definitions. get_fields() indeed prints out different values. however the swagger ui takes only the first method X and place its values for all the rest of the methods Y and Z.
an attempt to generate a unique name for each method/schema did not succeed.
![Screenshot - 2020-06-05T232748 791](https://user-images.githubusercontent.com/3123672/83924207-531aac00-a784-11ea-8a48-d8debbddf7bb.png)

**Comment by tfranzel** [comment]
sry but i do not quite understand what it is you're trying to accomplish. can you provide more context?

that schema look weird and i don't understand what hides behing your X, Y, Z.

**Comment by MahmoudAljabary** [comment]
```
from rest_framework import serializers
from random import random

class GenericSerializer(serializers.Serializer):
    def __init__(self, custom_class_name, custom_fields):
        self.__class__.__name__ = str(random())
        self.custom_fields = custom_fields

    def get_fields(self):
        return self.custom_fields
```
X, Y, and Y methods calls this GenericSerializer with different fields. however, the output only take the fields and name serializer name of X and give it to the rest. the end goal is to use only this one GenericSerializer. 
So this:
@extend_schema(
        request=YourRequestSerializer,
        responses=YourResponseSerializer,
        # more customizations
    )
becomes this:
@extend_schema(
        request=GenericSerializer,
        responses=GenericSerializer,
        # more customizations
    )

**Comment by MahmoudAljabary** [comment]
i fixed it by restructuring the GenericSerializer class for each method.

**Comment by tfranzel** [comment]
@MahmoudAljabary  glad you solved it otherwise, but since i know understand the problem let me shed some light.

if you have a generic "meta" serializer, DRF (and for that matter spectacular) has no way of knowing what fields are in there, because its not specified yet. i suppose you init the generic serializer in the method body. we do not and cannot run/inspect the bodies. afais the class in itself is just a container without actual field info. 

what might solve your problem is this:
```python
@extend_schema(
        request=GenericSerializer(None, YOUR_FIELD_LIST),
        responses=GenericSerializer(None, YOUR_FIELD_LIST),
)
```

that way spectacular can process a serializer instance (and not an empty class) that actually has some fields specified.
