### ISSUE TITLE
Get a specific openapi version (3.0.0)

### ISSUE THREAD

**Issue by rajmohanjiffy** [tfranzel/drf-spectacular#799]
Hi,
For my project, we have to upload the openapi spec to another tool (this happens during every build).
That tool supports only 3.0.0 version of openapi.
But, drf-spectacular provides openapi schema with version 3.0.3
This causes the upload to fail.
```
openapi: 3.0.3
info:
```
I checked all the setting parameters, but was not able to find a method to convert it to 3.0.0 openapi version.
Would it be possible to let me know how this can be solved?

Rajmohan

**Comment by tfranzel** [comment]
drf-spectacular is written around OpenAPI 3.0.3 at the moment. Looking at the diff between 3.0.0 and 3.0.3, it seems that there are not that many changes. There are differences for OAuth and a few other minors I believe.

As a hotfix I would recommend writing a [postprocessing hook](https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-6-postprocessing-hooks) that changes the version and then look if that tool of yours will work with that. It looks like you could get away with that, but your mileage may vary.

Sidenote: I don't think we should complicate spectacular by adding support for a 5 year old specification that already has 4 newer versions since then.

**Comment by rajmohanjiffy** [comment]
Thank you very much @tfranzel 
I will go ahead with this approach only
