### ISSUE TITLE
Download openapi json file locally during build

### ISSUE THREAD

**Issue by elaamrani** [tfranzel/drf-spectacular#840]
**Describe the bug**
I would like to download the drf-spectacular openapi schema into the project repository during my project build stage so that I can use it for CI/CD purposes later. Is that possible?

**To Reproduce**
python manage.py collectstatic

**Expected behavior**
Collectstatic or whatever other command downloads the file into local repository.

Thanks!

**Comment by tfranzel** [comment]
Hi,

`collectstatic` is meant of static files, though we also provide a CLI command for generating the schema in the console. You can use `spectacular --help` to inspect the options.

```bash
./manage.py spectacular --file schema.yml
```
https://github.com/tfranzel/drf-spectacular#take-it-for-a-spin

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Comment by ddelange** [comment]
hi @tfranzel :wave:

is there a url to serve `openapi.json`?

with or without `collectstatic` (preferably with, as it'll be cached by the CDN if we use `whitenoise.storage.CompressedManifestStaticFilesStorage`)

analogous to `/docs/schema` serving the yaml?

**Comment by tfranzel** [comment]
Sure there is. `/docs/schema?format=json`. This just uses standard DRF renderer selection via query param.

You can also select the output with a `ACCEPT: application/vnd.oai.openapi+json` or just `ACCEPT: application/json` header.

> edit: found drf_spectacular.views.SpectacularJSONAPIView. does it cache?

that is just a convenience view. the regular one can serve both.

> edit: found drf_spectacular.views.SpectacularJSONAPIView. does it cache?

No it does not cache. We never implemented it because there are a few dynamic things going and it was never such a pain point to invest the time. We do allow user-tailored rendered schemas with various variations in terms of i18n, format, versioning and so on. It is not just "cache one yaml an be done with it".
