### ISSUE TITLE
`drf_social_oauth2` endpoints in schema generation

### ISSUE THREAD

**Issue by konsalex** [tfranzel/drf-spectacular#850]
**Describe the bug**
Not a bug per-se, rather than a discussion of how `drf-spectacular` can incorporate some endpoints provided by [drf_social_oauth2](https://github.com/wagnerdelima/drf-social-oauth2).

Currently the `/token` endpoint is linked to a [`TokenView` class ](https://github.com/wagnerdelima/drf-social-oauth2/blob/master/drf_social_oauth2/views.py#L39), and when I generate the schema I receive the error.

```
Error #4: TokenView: unable to guess serializer. This is graceful fallback handling for APIViews. Consider using GenericAPIView as view base class, if view is under your control. Ignoring view for now.
```

I was curious if there is any I could override this so I can generate the proper schema for this endpoint, as I know beforehand what parameters it expects etc.

**To Reproduce**
Install [the library](https://github.com/wagnerdelima/drf-social-oauth2) and try to create the schema.

**Comment by tfranzel** [comment]
Hi, since this is a library you should use extensions, i.e. for source that is inaccessible to you.
https://drf-spectacular.readthedocs.io/en/latest/customization.html#replace-views-with-openapiviewextension

make sure you read the introduction:
https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-5-extensions

This would look something like this, but you could probably get away with just adding a non-functional serializer_class
https://drf-spectacular.readthedocs.io/en/latest/blueprints.html#dj-stripe

**Comment by konsalex** [comment]
Thanks for the guidance @tfranzel
