### ISSUE TITLE
Encountered 2 components with identical names

### ISSUE THREAD

**Issue by MahmoudAljabary** [tfranzel/drf-spectacular#90]
When reusing the same schema model. i encounter the following: Warning #1: Encountered 2 components with identical names "Error". This will very likely result in an incorrect schema. Try renaming one.
Is there is a way to overcome this, disable this or hide it?

**Comment by tfranzel** [comment]
If you have 2 serializers with identical name spectacular notifies your of the conflict. spectacular cannot decide for you what a proper name is. it only has `Error` to go with and that produces a conflict. to resolve it you have to options:

1. rename one serializer
2. use the ``ref_name`` feature ported from ``drf-yasg`` on one. https://drf-spectacular.readthedocs.io/en/latest/drf_yasg.html?highlight=ref_name#from-drf-yasg-to-openapi-3
that is an attribute on the serializer ``Meta`` class. it overrides default name generation.

this is related to #51. default collision resolution is a pending change, but would just add a random suffix anyway as an intermediate solution to have a correct schema even it is not nice looking.

**Comment by jayvdb** [comment]
A related issue I am running into is that the Router ordering of paths is not understood by the schema generator, which makes the current handling of identical names especially painful.  See https://github.com/tfranzel/drf-spectacular/issues/92

**Comment by MahmoudAljabary** [comment]
@tfranzel adding a random suffix does indeed work, but as you mentioned is not nice looking. suppose "Error" model is used in 10 endpoints. then we have Error1, Error2 .... Error10.
I think if we can find a way to catch and ignore the warning, might be a better approach.

**Comment by tfranzel** [comment]
@jayvdb we will deal with that in #92 

@MahmoudAljabary you have to understand that each ``Serializer`` needs a unique name for the schema to not be broken for client generation. To me, it sounds a bit weird that you have 10 different Error serializers.  spectacular can only utilize the class name and `ref_name`, as there is no other processable information for uniquely naming the component.

with that warning the spectacular notifies you that it found an issue. for the warning to disappear we would need a resolution for this issue. can you make a alternate suggestion for uniquely name the serializers? because i currently don't see no other good options here.

**Comment by tfranzel** [comment]
closing because this more a feature than a bug. even with a different conflict solution the warning would remain to inform about the "auto conflict resolution" component names.
