### ISSUE TITLE
PolymorphicProxySerializer, Is it possible to display example data for each serializers field?

### ISSUE THREAD

**Issue by Gilions** [tfranzel/drf-spectacular#905]
The API uses PolymorphicProxySerializer.

Example:
```python
from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import extend_schema, OpenApiParameter, PolymorphicProxySerializer
from rest_framework import serializers
from rest_framework.generics import ListAPIView


class First(serializers.Serializer):
    product_id = serializers.CharField()
    quantity = serializers.IntegerField()
    price = serializers.FloatField()


class Second(serializers.Serializer):
    productId = serializers.CharField()
    region = serializers.IntegerField()
    quantity = serializers.IntegerField()


class Third(serializers.Serializer):
    productId = serializers.CharField()
    region = serializers.IntegerField()


class TestView(ListAPIView):
    @extend_schema(
        description='Test',
        parameters=[
            OpenApiParameter('api_key', OpenApiTypes.STR, OpenApiParameter.QUERY, True),
        ],
        responses={201: PolymorphicProxySerializer(
            component_name='Response',
            serializers=[First, Second, Third],
            resource_type_field_name='Response',
            many=True
        )}
    )
    def get(self, *args, **kwargs):
        return super().get(*args, **kwargs)
    
```

UI Swagger looks like:

<img width="1422" alt="Screenshot 2022-12-28 at 13 15 58" src="https://user-images.githubusercontent.com/68146917/209804198-197a7972-08c9-4000-9866-cbfba289bfbf.png">

Is it possible to add example data for each field, like here?

<img width="291" alt="Screenshot 2022-12-28 at 13 21 34" src="https://user-images.githubusercontent.com/68146917/209804592-df93f8ac-6dfb-4130-9902-672fb249ecb6.png">

Thanks for your help!

**Comment by tfranzel** [comment]
Hi @Gilions,

we currently do not support examples on a field level. This is due to DRF not allowing to add extra params to serializer fields out of the box. 

We do support adding examples on a serializer level though: You can either add them to the serializer or the view via decoration:

https://github.com/tfranzel/drf-spectacular/blob/350529ad8f670e4d5e288218f582a48715d05d41/tests/test_examples.py#L15-L16

https://github.com/tfranzel/drf-spectacular/blob/350529ad8f670e4d5e288218f582a48715d05d41/tests/test_examples.py#L80

Also, this is more flexible and allows to add tailored list of examples, which would conflict with the "less powerful" field level examples.
