### ISSUE TITLE
How to automatically render schema fields?

### ISSUE THREAD

**Issue by Gilions** [tfranzel/drf-spectacular#906]
Is there a setting that will automatically display field data?

Settings:
```python
SPECTACULAR_SETTINGS = {
    'SERVE_INCLUDE_SCHEMA': False,
    # Permission
    'SERVE_AUTHENTICATION': ['rest_framework.authentication.SessionAuthentication'],
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAuthenticated'],
    # UI settings
    'SWAGGER_UI_DIST': 'SIDECAR',  # shorthand to use the sidecar instead
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'SCHEMA_PATH_PREFIX_TRIM': True,
}
```
In the swagger, the data is reflected in this form:

<img width="449" alt="Screenshot 2022-12-28 at 08 49 16" src="https://user-images.githubusercontent.com/68146917/209871346-961d5546-4cb2-4561-8c8d-282f52031a4f.png">

Is it possible to automatically expand the information of these fields?

Example like here:

<img width="858" alt="Screenshot 2022-12-28 at 17 24 41" src="https://user-images.githubusercontent.com/68146917/209871484-d310fda0-8972-43a7-88d2-3431ff8e4cc5.png">

**Comment by tfranzel** [comment]
Not that I am aware of. This would be a Swagger UI setting though, since this is exclusively display related and all the necessary information is already in the schema itself.

Available settings:
https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

Where to put it:
https://github.com/tfranzel/drf-spectacular/blob/b195317ba7e9b89333be261b485558888ca69ffa/drf_spectacular/settings.py#L62

**Comment by Gilions** [comment]
@tfranzel, thank you for answer.

That setting solved the problem

```python
'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayOperationId': True,
        'defaultModelsExpandDepth': -1,
        'defaultModelExpandDepth': 3,
    }
```
