### ISSUE TITLE
A way to declare multiple responses(serialisers) per http status_code?

### ISSUE THREAD

**Issue by diego351** [tfranzel/drf-spectacular#914]
Is there such thing? In openapi 3.x there is something like `oneOf` clausule. Also, there is such clausule to make as `allOf`?

**Comment by tfranzel** [comment]
sure we do: https://github.com/tfranzel/drf-spectacular/blob/24b8a9890d59900d102490a48e286d08cdcc7ab5/drf_spectacular/utils.py#L26

This generates `oneOf`s. There is even a bit more logic behind this feature when you use the `discriminator`. This is relevant for code generation, otherwise you can do `resource_type_field_name=None`



Here is an example from the tests. You can also write this inline, this was just factored out for brevity.

https://github.com/tfranzel/drf-spectacular/blob/7f4b887f0522c1f685b55f9cd7253af55ef4552f/tests/test_polymorphic.py#L55-L64
