### ISSUE TITLE
Support example generation with min_value and max_value in Decimal field

### ISSUE THREAD

**Issue by gorkemarslan** [tfranzel/drf-spectacular#919]
**Describe the bug and To Reproduce**

Even though I restrict `price` field by `min_value` and `max_value` parameters of `serializers.DecimalField`, random values including negative ones (`'-1234'`) and strings ('`-`' and '`.`') are generated as example values in the generated Swagger documentation.

```python
class PriceSerializer(serializers.Serializer):
    price = serializers.SerializerMethodField()

    def get_price(self, obj) -> serializers.DecimalField(max_digits=5, decimal_places=2, min_value="0.00", max_value="999.99"):
        return obj.price
```

**Expected behavior**
Valid random examples should be generated without using explicit [examples](https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-4-extend-schema-serializer).

**Comment by tfranzel** [comment]
Hi,

we do not generate examples. Either you explicitly write examples yourself or you rely on the UI (e.g. SwaggerUI) to generate something meaningful, which is what usually happens. The UI tries to put some reasonable values based on the the types (integer, uuid, str) the schema provides. There is not much more magic going on. For everything more involved we provide the option to inject explicit examples.

Having better introspection into field example value generation would be an upstream request (Swagger, Redoc). You will notice that we have no `examples`* in the schema, unless you explicitly write them.




[*] not entirely true, because pagination has built-in examples but that is a different story.
