### ISSUE TITLE
Field with default value appears as optional in schema

### ISSUE THREAD

**Issue by StewartJ-SSG** [tfranzel/drf-spectacular#920]
**Describe the bug**
My code has the following model with a boolean field, `published`, with a default value of `false`
```
class PublishableModel(models.Model):
    """Fields used to determine if and when something is published."""
    published = models.BooleanField(default=False)
    publish_date = models.DateTimeField(blank=True, null=True)

```

However, the schema that drf-spectacular produces shows published as optional.

For example:
```
    /**
     * 
     * @type {boolean}
     * @memberof Article
     */
    published?: boolean;
```

**Expected behavior**
Since there is a default value - all response types should appear in the required section of the model for methods that return an Article but optional for methods that are creating an Article.

Is there a way to distinguish between request and response values being required in the schema?

**Comment by tfranzel** [comment]
As you noticed there is an asymmetry between request and response and OpenAPI cannot model this with just one component.

By default, spectacular generates one component and it needs to make this field optional or otherwise the request would require it making it "not optional". We need to go the permissive route in this case.

If you want more precise modeling of requests & responses, I would recommend enabling `COMPONENT_SPLIT_REQUEST`

```python
SPECTACULAR_SETTINGS = {
    "COMPONENT_SPLIT_REQUEST": True,
```

**Comment by StewartJ-SSG** [comment]
Thanks for your reply. I've tried adding the following to my settings.py, and restarting my django but it makes no change in schema. I'm not sure what I'm doing incorrectly. 

`
    SPECTACULAR_SETTINGS = {
        'TITLE': 'RIABiz.com API',
        'DESCRIPTION': 'API documentation for RIABiz app',
        'VERSION': '2.0.2',
        "COMPONENT_SPLIT_REQUEST": True,
        'ENUM_ADD_EXPLICIT_BLANK_NULL_CHOICE': False,
    }
`

**Comment by tfranzel** [comment]
your snippet seems indented.... `SPECTACULAR_SETTINGS` is on the root level of `settings.py`, not nested in `REST_FRAMEWORK`

Your snippet has to work (if located at the right place)

```python
REST_FRAMEWORK = {
 ...
}

SPECTACULAR_SETTINGS = {
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": """{
        deepLinking: true,
        displayOperationId: true,
    }""",
    "VERSION": "0.0.1",
    ...
}

**Comment by StewartJ-SSG** [comment]
Sorry. Stupid error. I had another `SPECTACULAR_SETTINGS` at the end of the file that was overwriting it. I had hoped I deleted my question in time. 

It's now creating two components for each model - the request and response - my next question is how do I annotate my model so the field with the default value show up correctly required in the response?

```
class PublishableModel(models.Model):
    """Fields used to determine if and when something is published."""
    published = models.BooleanField(default=False)
    publish_date = models.DateTimeField(blank=True, null=True)

    publish_status = PublicationStatusQuerySet.as_manager()

    class Meta:
        abstract = True
```

published will always have a value in every response object that inherits from Publishable. But the schema still shows it as optional. For example, using the typescript generator:
```
export interface Listing {
    /**
     * 
     * @type {boolean}
     * @memberof Listing
     */
    published?: boolean;
.
.
.
```

**Comment by tfranzel** [comment]
Your model is fine. The issue is that DRF does not carry over `default` values when converting a model to a `serializers.ModelSerializer`. The `default` info is simply lost in translation. 

If you manually give `default` values to **serializer fields**, it will show up properly. The only thing I can advice is creating a `ModelSerializer` and manually override the `published` field with a `published = serializers.BooleanField(default=False)`. Alternatively you can use `extra_kwargs`. Not much else can be done here.
