### ISSUE TITLE
ViewSets throwing error after adding custom middleware

### ISSUE THREAD

**Issue by edmundsj** [tfranzel/drf-spectacular#930]
**Describe the bug**
I recently added a piece of middleware that adds an "organization" to the `request` object. This middleware works, all my tests pass, and the backend itself responds appropriately and as expected. However, `drf-spectacular` is throwing exceptions when I try to extract the schema from the views that use the new field.

**To Reproduce**
1. Create a new middleware and add it to settings.py that adds a new field to the `request` object.
```
class ProblemChildMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):

        request.new_field = None
        response = self.get_response(request)

        return response
```
2. Create a new ViewSet that uses that new field in `get_queryset`:
```
class ProblemViewSet(ModelViewSet):
    serializer_class = ProblemModelSerializer

    def get_queryset(self):
        new_field = self.request.new_field
        queryset = ProblemModel.objects.none()
        return queryset
```
DRF-spectacular will then throw an error:
```
/app/coaching/views/problem_views.py:155: Warning [ProblemViewSet]: Failed to obtain model through view's queryset due to raised exception. Prevent this either by setting "queryset = Model.objects.none()" on the view, checking for "getattr(self, "swagger_fake_view", False)" in get_queryset() or by simply using @extend_schema. (Exception: 'Request' object has no attribute 'new_field')
```

**Expected behavior**
I expect my middleware to be run by `drf-spectacular` and for custom middleware modifying the request object not to cause issues with schema extraction.

**Comment by edmundsj** [comment]
While there is a [workaround](https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-get-queryset-depends-on-some-attributes-not-available-at-schema-generation-time), it adds logic internal to the `ViewSet`, which is not ideal. Is there no way to specify fields that need to be pre-populated at schema generation time, or plans to fix this?

**Comment by tfranzel** [comment]
So this is expected behavior. We do not run the middleware stack, as there may happen side effects we do not want, like querying databases or caches. Also note that the request send through there is still a mock request. We explitily refrain from anything that might contact the DB, so that schema can be generated offline vial CLI. This will likely create a lot more issues than solving problems.

> Create a new middleware and add it to settings.py that adds a new field to the request object.

Where is the data for this added request field coming from? I'm assuming this is not happening in a vacuum in practice.

> While there is a [workaround](https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-get-queryset-depends-on-some-attributes-not-available-at-schema-generation-time), it adds logic internal to the ViewSet, which is not ideal. Actually scares me a little.

Not sure what is scary about that solution. Returning an empty queryset should be pretty safe actually.

There is another potential solution. You could add `queryset = ProblemModel.objects.none()` to the view while keeping the original `get_queryset`. We attempt to retrieve the `queryset` class attr before calling the `get_queryset` method.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.
