### ISSUE TITLE
How to override `SerializerMethodField` to mark as not required

### ISSUE THREAD

**Issue by johnthagen** [tfranzel/drf-spectacular#979]
We have a `Serializer` such as:

```py
class MyModelSerializer(MyModelSerializer):
    field = SerializerMethodField()

    def get_field(self, instance: MyModel) -> str | None:
        if instance.other_field:
            return None
        return "Hello World"
```

This creates a schema such as:

```
field* | string
nullable: true
readOnly: true
```

So this is a required, nullable field. This is the correct output.

_But_...

Some OpenAPI clients (such as the [Java generator in OpenAPI](https://openapi-generator.tech/docs/generators/java)) do not support fields that are both required _and_ nullable 😢 .

Is there a way to override a `SerializerMethodField` to remove the `required` attribute? I didn't immediately see how [`@extend_schema_field`](https://drf-spectacular.readthedocs.io/en/latest/customization.html#step-3-extend-schema-field-and-type-hints) could be used for this.

**Comment by tfranzel** [comment]
I think we accounted for this in

https://github.com/tfranzel/drf-spectacular/blob/28b858e83e8341c806cc23e7cb09ea1f06b2b357/drf_spectacular/settings.py#L38

Set it to `True`.

**Comment by johnthagen** [comment]
Yep, that was it. Thank you!

**Comment by tfranzel** [comment]
> Not asking for a feature at all since this is niche,

no worries. I get your point. No, I don't think there is an easy way to do exactly this, except for hacking spectacular.  

The existing feature was meant as a simple but effective solution. Building variations for different generator target will certainly get tedious and thus I would prefer not to.

Since you are using Java, are you sure you don't need it for `id`? Last time I checked, it produced code that was not really usable due to `id` not being writable but also not allowed to be null, which created a dilemma on object creation.

**Comment by johnthagen** [comment]
> Building variations for different generator target will certainly get tedious and thus I would prefer not to.

Absolutely.

We're going to also explore simply trying to contribute a fix upstream to the Java generator so that it handles this standard OpenAPI 3 use case better/correctly.

Thanks for the discussion!
