### ISSUE TITLE
Handle choice fields with the same values

### ISSUE THREAD

**Issue by danihodovic** [tfranzel/drf-spectacular#992]
I'm working on a rather large API which happens to use third party library values for choice fields (Celery task states). When generating API docs and more importantly API clients drf-spectacular creates a random name for the enum:

```
Warning: enum naming encountered a non-optimally resolvable collision for fields named "status". The same name has been used for multiple choice sets in multiple components. The collision was resolved with "StatusBe6Enum". add an entry to ENUM_NAME_OVERRIDES to fix the naming.

Schema generation summary:
Warnings: 1 (1 unique)
Errors:   0 (0 unique)
```

The resulting enum is named StatusBe6Enum which I think is poor naming. How can I workaround this issue?

**Comment by tfranzel** [comment]
Hi! That is known and to be expected. `status` is a common situation for this to pop up. It is essentially due to DRF/Django providing no name for the enum set. All we can do is guess a name and if that appears to not be 100% safe, we add a suffix and emit a warning. 

Use `ENUM_NAME_OVERRIDES` where needed to assign explicit names to choice sets: https://drf-spectacular.readthedocs.io/en/latest/faq.html#i-get-warnings-regarding-my-enum-or-my-enum-names-have-a-weird-suffix

The warning should go away then.

**Comment by tfranzel** [comment]
closing this issue for now. feel free to comment if anything is missing or not working and we will follow-up.

**Comment by EduardoJM** [comment]
> Use `ENUM_NAME_OVERRIDES` where needed to assign explicit names to choice sets

how? when i get the error:

```
Warning: encountered multiple names for the same choice set (XPTOEnum). This may be unwanted even though the generated schema is technically correct. Add an entry to ENUM_NAME_OVERRIDES to fix the naming.
```

Add it to the `ENUM_NAME_OVERRIDES`:

```python
SPECTACULAR_SETTINGS = {
    "ENUM_NAME_OVERRIDES": {
        'XPTOEnum': 'import.path.xpto',
    }
}
```

Really solve and remove warning.

But, how to solve the bellow error? what i need to add to the `ENUM_NAME_OVERRIDES`?

```
Warning: enum naming encountered a non-optimally resolvable collision for fields named "status". The same name has been used for multiple choice sets in multiple components. The collision was resolved with "StatusE08Enum". add an entry to ENUM_NAME_OVERRIDES to fix the naming.
```

Thanks

**Comment by tfranzel** [comment]
> Really solve and remove warning.

so this is solved, right?

 > But, how to solve the bellow error? what i need to add to the ENUM_NAME_OVERRIDES?

@EduardoJM, this is the most common field name this happens on. You have more than one `status` field in your API and they have different choices, hence the warning. DRF/Django throws away choice set names, which is why we can only use the serializer/model field name as reference. If that is not safe/unambiguous, we emit those warnings.

this should do it:

```python
SPECTACULAR_SETTINGS = {
    "ENUM_NAME_OVERRIDES": {
        'XPTOEnum': 'import.path.xpto',
        'SomeStatusEnum': 'import.path.status1',
        'OtherStatusEnum': 'import.path.status2',
    }
}
```
