### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by lokeish** [tfranzel/drf-spectacular#994]
## Authorization Value is not getting passed in get request

Below is the extend schema i am using.

```
@extend_schema(parameters=[
                OpenApiParameter(name='view', description='Type of view (Popular/All)', required=True, type=str),
                OpenApiParameter(name='user-type', description='Default Partner Value', required=True, default='partner', location=OpenApiParameter.HEADER),
                OpenApiParameter(name='Authorization', description='Default Partner Value', required=True, default='partner2', location=OpenApiParameter.HEADER)
                ],
                description='This API lists datasets',
                methods=["GET"],
                auth=None
            )
```

Below swagger settings im using in my settings.py

```
SPECTACULAR_SETTINGS = {
    'TITLE': 'GAP Project API',
    'DESCRIPTION': 'Genius AI Platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    },
    "SECURITY": [{"BearerAuth": []}],

}
```
Below Authorization header value is not present. Can any one help me to fix Authorization issue, i am trying to send bearer token.

<img width="1375" alt="image" src="https://github.com/tfranzel/drf-spectacular/assets/40191054/60a36c71-0a03-459b-bb46-3f63d2225968">

**Comment by tfranzel** [comment]
SwaggerUI does not like when you add an `Authorization`, because it usually manages this aspect for you through the Authorize button. 

Headers `Authorization`, `Content-Type, `Accept` have special meaning in Swagger/OpenAPI and cannot be overridden like that.

Using `APPEND_COMPONENTS` is a last measure. Usually there are better solutions. We do already support this automatically for the most important auth libs. If you have a custom solution, it is easy to write an extension: https://drf-spectacular.readthedocs.io/en/latest/customization.html#specify-authentication-with-openapiauthenticationextension

Example:

https://github.com/tfranzel/drf-spectacular/blob/2388a403b6c4358c332d2ad142bc9dbaeb5c9165/drf_spectacular/contrib/rest_framework_simplejwt.py#L62
